In [74]:
import pandas as pd
import numpy as np

In [75]:
# Creating DataFrames using a dictionary
people = {
    "first": [
        "Ashish", "Corey", "John", "Meera", "Arjun",
        "Sophia", "Liam", "Hannah", "Carlos", "Jisoo", np.nan, None, 'NA'
    ],
    "last": [
        "Khanagwal", "Anderson", "Doe", "Patel", "Singh",
        "Williams", np.nan, "Nguyen", "Garcia", "Kim", np.nan, np.nan, 'Missing'
    ],
    "email_address": [
        "ashishkhanagwal@gmail.com",
        "coreyschafar@gmail.com",
        "timdavid@gmail.com",
        None,
        "arjunsingh@gmail.com",
        "sophiawilliams@gmail.com",
        "liambrown@gmail.com",
        "hannahnguyen@gmail.com",
        "carlosgarcia@gmail.com",
        "jisookim@gmail.com",
        None,
        np.nan,
        'Anonymous@email.com'
    ],
    "age": [24, 27, 26, 25, 29, 31, 28, 24, 32, 26, None, None, 'Missing'],
}

## Cleaning data: casting datatypes and handling missing values
Cleaning data in pandas typically starts with getting the right dtypes for each column and then dealing with missing values in a principled way. Correct dtypes make operations faster and safer, while robust missing-value handling prevents errors and bias in analysis.

In [86]:
df = pd.DataFrame(people)

# To handle 'Missing' or any 'arbitrary' value we can do use numpy to replace those with np.nan.
df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)
df

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_12050/3590670241.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('Missing', np.nan, inplace=True)

     first       last              email_address   age
0   Ashish  Khanagwal  ashishkhanagwal@gmail.com  24.0
1    Corey   Anderson     coreyschafar@gmail.com  27.0
2     John        Doe         timdavid@gmail.com  26.0
3    Meera      Patel                       None  25.0
4    Arjun      Singh       arjunsingh@gmail.com  29.0
5   Sophia   Williams   sophiawilliams@gmail.com  31.0
6     Liam        NaN        liambrown@gmail.com  28.0
7   Hannah     Nguyen     hannahnguyen@gmail.com  24.0
8   Carlos     Garcia     carlosgarcia@gmail.com  32.0
9    Jisoo        Kim         jisookim@gmail.com  26.0
10     NaN        NaN                       None   NaN
11    None        NaN                        NaN   NaN
12     NaN        NaN        Anonymous@email.com   NaN

#### These show memory use, types, and where missing values appear.

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first          10 non-null     object
 1   last           9 non-null      object
 2   email_address  10 non-null     object
 3   age            10 non-null     float64
dtypes: float64(1), object(3)
memory usage: 548.0+ bytes

In [88]:
df.dtypes

first             object
last              object
email_address     object
age              float64
dtype: object

In [89]:
df.isna().sum()

first            3
last             4
email_address    3
age              3
dtype: int64

In [90]:
# df.dropna()
# drop any row with at least one NaN
# df.dropna(axis='index', how='any) -> This will drop the rows with at least one NaN.
# If we change 'how='any'' to 'all' then it will drop the row with all NaN values
df.dropna(axis='index', how='all')

     first       last              email_address   age
0   Ashish  Khanagwal  ashishkhanagwal@gmail.com  24.0
1    Corey   Anderson     coreyschafar@gmail.com  27.0
2     John        Doe         timdavid@gmail.com  26.0
3    Meera      Patel                       None  25.0
4    Arjun      Singh       arjunsingh@gmail.com  29.0
5   Sophia   Williams   sophiawilliams@gmail.com  31.0
6     Liam        NaN        liambrown@gmail.com  28.0
7   Hannah     Nguyen     hannahnguyen@gmail.com  24.0
8   Carlos     Garcia     carlosgarcia@gmail.com  32.0
9    Jisoo        Kim         jisookim@gmail.com  26.0
12     NaN        NaN        Anonymous@email.com   NaN

In [91]:
df.dropna(axis='index', how='all', subset=['email_address'])
# this will drop the rows with NaN value in the series 'email_address'

     first       last              email_address   age
0   Ashish  Khanagwal  ashishkhanagwal@gmail.com  24.0
1    Corey   Anderson     coreyschafar@gmail.com  27.0
2     John        Doe         timdavid@gmail.com  26.0
4    Arjun      Singh       arjunsingh@gmail.com  29.0
5   Sophia   Williams   sophiawilliams@gmail.com  31.0
6     Liam        NaN        liambrown@gmail.com  28.0
7   Hannah     Nguyen     hannahnguyen@gmail.com  24.0
8   Carlos     Garcia     carlosgarcia@gmail.com  32.0
9    Jisoo        Kim         jisookim@gmail.com  26.0
12     NaN        NaN        Anonymous@email.com   NaN

In [92]:
df.dropna(axis='index', how='all', subset=['last', 'email_address'])
# This command removes rows where both last and email_address are missing, but keeps rows where at least one of them has a value.

     first       last              email_address   age
0   Ashish  Khanagwal  ashishkhanagwal@gmail.com  24.0
1    Corey   Anderson     coreyschafar@gmail.com  27.0
2     John        Doe         timdavid@gmail.com  26.0
3    Meera      Patel                       None  25.0
4    Arjun      Singh       arjunsingh@gmail.com  29.0
5   Sophia   Williams   sophiawilliams@gmail.com  31.0
6     Liam        NaN        liambrown@gmail.com  28.0
7   Hannah     Nguyen     hannahnguyen@gmail.com  24.0
8   Carlos     Garcia     carlosgarcia@gmail.com  32.0
9    Jisoo        Kim         jisookim@gmail.com  26.0
12     NaN        NaN        Anonymous@email.com   NaN

In [95]:
df.isna()

# It checks every cell in your DataFrame.
# If the value is missing (NaN), it returns True.
# If the value is present, it returns False.
# So the output is a Boolean DataFrame of the same shape as your original one.

    first   last  email_address    age
0   False  False          False  False
1   False  False          False  False
2   False  False          False  False
3   False  False           True  False
4   False  False          False  False
5   False  False          False  False
6   False   True          False  False
7   False  False          False  False
8   False  False          False  False
9   False  False          False  False
10   True   True           True   True
11   True   True           True   True
12   True   True          False   True

In [98]:
df.fillna(0)
# It will fill all the NaN values with 0.

     first       last              email_address   age
0   Ashish  Khanagwal  ashishkhanagwal@gmail.com  24.0
1    Corey   Anderson     coreyschafar@gmail.com  27.0
2     John        Doe         timdavid@gmail.com  26.0
3    Meera      Patel                          0  25.0
4    Arjun      Singh       arjunsingh@gmail.com  29.0
5   Sophia   Williams   sophiawilliams@gmail.com  31.0
6     Liam          0        liambrown@gmail.com  28.0
7   Hannah     Nguyen     hannahnguyen@gmail.com  24.0
8   Carlos     Garcia     carlosgarcia@gmail.com  32.0
9    Jisoo        Kim         jisookim@gmail.com  26.0
10       0          0                          0   0.0
11       0          0                          0   0.0
12       0          0        Anonymous@email.com   0.0

### Casting datatypes
- Force a specific dtype with astype:

In [101]:
# If any of the series contains NaN values and otger values as Integers, then we have to typecast our all values
# into float because, NaN is float in natue
type(np.nan)

float

In [103]:
df['age'] = df['age'].astype('float')

In [106]:
df['age'].mean()

np.float64(27.2)