## Converting the datatype of a particular column.

In [56]:
import pandas as pd
import numpy as np

In [57]:
# Creating DataFrames using a dictionary
people = {
    "first": [
        "Ashish", "Corey", "John", "Meera", "Arjun",
        "Sophia", "Liam", "Hannah", "Carlos", "Jisoo"
    ],
    "last": [
        "Khanagwal", "Anderson", "Doe", "Patel", "Singh",
        "Williams", "Brown", "Nguyen", "Garcia", "Kim"
    ],
    "email_address": [
        "ashishkhanagwal@gmail.com",
        "coreyschafar@gmail.com",
        "timdavid@gmail.com",
        "meerapatel@gmail.com",
        "arjunsingh@gmail.com",
        "sophiawilliams@gmail.com",
        "liambrown@gmail.com",
        "hannahnguyen@gmail.com",
        "carlosgarcia@gmail.com",
        "jisookim@gmail.com",
    ],
    "age": [24, 27, 26, 25, 29, 31, 28, 24, 32, 26],
    "Profession": [
        "AI Engineer", "Tutor", "Software Developer", "Data Scientist", "Product Manager",
        "UX Designer", "DevOps Engineer", "Research Analyst", "Systems Architect", "ML Engineer"
    ],
    "Company": [
        "Meta", "YouTube", "Google", "Microsoft", "Amazon",
        "Apple", "Netflix", "Tesla", "IBM", "OpenAI"
    ],
    "Score": [85, 90, 88, 92, 89, 87, 91, 86, 93, 95]
}

In [58]:
df = pd.DataFrame(people)
df

,first,last,email_address,age,Profession,Company,Score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

### 1. Using .astype()
- This is the most common and easiest way.

In [59]:
df['age'] = df['age'].astype(str)
# This will covert data type of age from int to string.
df['age']

df['Score'] = df['Score'].astype(float)
# This will convert the data type of score from int to float.
df['Score']

0    85.0
1    90.0
2    88.0
3    92.0
4    89.0
5    87.0
6    91.0
7    86.0
8    93.0
9    95.0
Name: Score, dtype: float64

### 2. Using `pd.to_numeric()`, `pd.to_datetime()`, `pd.to_timedelta()`
- These are special functions for certain datatypes.

In [60]:
# To numbers (int/float):
df['age'] = pd.to_numeric(df['age'])
df['age']
# Converted from string to integer.

0    24
1    27
2    26
3    25
4    29
5    31
6    28
7    24
8    32
9    26
Name: age, dtype: int64

In [61]:
# To check data types of the dataframe.
df.dtypes

first             object
last              object
email_address     object
age                int64
Profession        object
Company           object
Score            float64
dtype: object

## Adding and Removing rows and columns
Adding and removing rows and columns in a pandas DataFrame is a common operation when preparing or cleaning up your data. Here’s how to do it in a clear, friendly way with practical examples:

## Adding Columns
Assign a new column by name:

In [62]:
df['full name'] = df['first'] + ' ' + df['last']

In [63]:
df

,first,last,email_address,age,Profession,Company,Score,full name
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim

## Removing Columns
Using drop:

In [64]:
df.drop(columns=['first', 'last'], inplace = True)
df
# This will remove the 'first' and 'last' columns from the dataframe.
# Removes the column “column_name” from the DataFrame. Use axis=1 for columns.

,email_address,age,Profession,Company,Score,full name
0,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal
1,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson
2,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe
3,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel
4,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh
5,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams
6,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown
7,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen
8,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia
9,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim

In [65]:
df['full name'].str.split(' ', expand = True)
# this is how full name column will be split into two seperate columns

        0          1
0  Ashish  Khanagwal
1   Corey   Anderson
2    John        Doe
3   Meera      Patel
4   Arjun      Singh
5  Sophia   Williams
6    Liam      Brown
7  Hannah     Nguyen
8  Carlos     Garcia
9   Jisoo        Kim

In [66]:
# Adding new columns and assigning value at the same time.
df[['first', 'last']] = df['full name'].str.split(' ', expand=True)
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim

## Adding Row

In [67]:
# New row as DataFrame, and other than 'fist' all values will be set to NaN.
new_row = pd.DataFrame({'first': ['Tony']})
df = pd.concat([df, new_row], ignore_index=True)

In [68]:
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
10,NaN,NaN,NaN,NaN,NaN,NaN,Tony,NaN

## Removing Rows
Drop rows by index:

In [69]:
df.drop(10, axis = 0, inplace=True)
# Removes the row with the specified index (use axis=0 for rows).

In [70]:
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim

# Drop multiple rows by index:
`df.drop([0, 2], axis=0, inplace=True)`

## Adding two DataFrames
### 1. Combine by Adding Rows (pd.concat)
Use case: You want one DataFrame under the other, with the same columns.

In [71]:
people = {
  'first': ['Tony', 'Steve'],
  'last' : ['Stark', 'Rogers'],
  'email_address': ['tonystark@avenge.com', 'steverogers@avenge.com']
}

df2 = pd.DataFrame(people)
df2

   first    last           email_address
0   Tony   Stark    tonystark@avenge.com
1  Steve  Rogers  steverogers@avenge.com

In [72]:
df = pd.concat([df, df2], ignore_index=True)
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers

## Sorting Data
### Sort by values
- Sort a DataFrame by one column:

In [73]:
df.sort_values(by='age') # In Ascending order
# df.sort_values(by='age', ascending=False) # In Descending order

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers

## Sort by multiple columns with different orders:

In [74]:
df.sort_values(by=['age', 'Score'], ascending=[True, False])
# First sorts by age, then within same age sort by score high->low.

,email_address,age,Profession,Company,Score,full name,first,last
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers

In [75]:
df.sort_values(by=['last', 'first'], ascending = [False, True], inplace=True)

In [76]:
df

,email_address,age,Profession,Company,Score,full name,first,last
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson

In [77]:
# In order to sort a specific series, we can do like this:-
df['first'].sort_values()

4      Arjun
0     Ashish
8     Carlos
1      Corey
7     Hannah
9      Jisoo
2       John
6       Liam
3      Meera
5     Sophia
11     Steve
10      Tony
Name: first, dtype: object

## Control missing values placement:
- Moves NaN values to the top instead of the default bottom

In [78]:
df.sort_values(by='age', na_position='first')

,email_address,age,Profession,Company,Score,full name,first,last
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia

## Ignore original index in the result:
- Resets the index in the sorted output.

In [79]:
df.sort_values(by='age', ignore_index=True)

,email_address,age,Profession,Company,Score,full name,first,last
0,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
1,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
2,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
3,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
4,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
5,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
8,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
9,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers

## Sort by index labels
### 1. Sort rows by index:

In [80]:
df.sort_index()
# Orders the DataFrame by its row labels

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers

### 3. Sort columns by their names:

In [81]:
df.sort_index(axis=1)
# Pandas looks at the column names as strings and sorts them in ASCII/lexicographical order, not by any “logical order” you might expect.

,Company,Profession,Score,age,email_address,first,full name,last
5,Apple,UX Designer,87.0,31.0,sophiawilliams@gmail.com,Sophia,Sophia Williams,Williams
10,NaN,NaN,NaN,NaN,tonystark@avenge.com,Tony,NaN,Stark
4,Amazon,Product Manager,89.0,29.0,arjunsingh@gmail.com,Arjun,Arjun Singh,Singh
11,NaN,NaN,NaN,NaN,steverogers@avenge.com,Steve,NaN,Rogers
3,Microsoft,Data Scientist,92.0,25.0,meerapatel@gmail.com,Meera,Meera Patel,Patel
7,Tesla,Research Analyst,86.0,24.0,hannahnguyen@gmail.com,Hannah,Hannah Nguyen,Nguyen
9,OpenAI,ML Engineer,95.0,26.0,jisookim@gmail.com,Jisoo,Jisoo Kim,Kim
0,Meta,AI Engineer,85.0,24.0,ashishkhanagwal@gmail.com,Ashish,Ashish Khanagwal,Khanagwal
8,IBM,Systems Architect,93.0,32.0,carlosgarcia@gmail.com,Carlos,Carlos Garcia,Garcia
2,Google,Software Developer,88.0,26.0,timdavid@gmail.com,John,John Doe,Doe
6,Netflix,DevOps Engineer,91.0,28.0,liambrown@gmail.com,Liam,Liam Brown,Brown
1,YouTube,Tutor,90.0,27.0,coreyschafar@gmail.com,Corey,Corey Anderson,Anderson

## Sort MultiIndex by specific level:
- Sorts using a particular index level in a hierarchical index.

In [82]:
df.index

Index([5, 10, 4, 11, 3, 7, 9, 0, 8, 2, 6, 1], dtype='int64')

In [83]:
df.columns

Index(['email_address', 'age', 'Profession', 'Company', 'Score', 'full name',
       'first', 'last'],
      dtype='object')

### `df.sort_index(level='')`
## What level means
- level is used when your rows or columns have a MultiIndex (multiple levels of indexing).
- It tells pandas: “Sort by this level of the index.”

In [84]:
df

,email_address,age,Profession,Company,Score,full name,first,last
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson

## Grouping And Aggregating

In [85]:
df2 = pd.DataFrame({
    'Dept': ['A','A','B','B','B'],
    'Employee': ['x','y','u','v','w'],
    'Salary': [70, 80, 60, 50, 90],
    'Bonus': [7, 8, 6, 5, 9]
})

In [86]:
dept_grp = df2.groupby(['Dept'])

dept_grp['Employee'].count()

# Count rows per group: df.groupby('Dept')['Employee'].count() shows how many entries per department.

Dept
A    2
B    3
Name: Employee, dtype: int64

In [87]:
# Multiple columns grouping: df.groupby(['Dept','Employee']).size() gives a frequency table of combinations.
df2.groupby(['Dept', 'Employee']).size()

Dept  Employee
A     x           1
      y           1
B     u           1
      v           1
      w           1
dtype: int64

In [88]:
# Single aggregation: df.groupby('Dept')['Salary'].mean() computes the average salary per department
dept_grp['Salary'].mean()

Dept
A    75.000000
B    66.666667
Name: Salary, dtype: float64

In [89]:
# Multiple aggregations on one column:
dept_grp['Salary'].agg(['min', 'median', 'mean', 'max'])

      min  median       mean  max
Dept
A      70    75.0  75.000000   80
B      50    60.0  66.666667   90

In [90]:
# Aggregations per column with dict:
# This allows per-column functions in one pass
dept_grp.agg({'Salary': 'mean', 'Bonus': 'sum'})

         Salary  Bonus
Dept
A     75.000000     15
B     66.666667     20

In [91]:
# Named aggregations to control output names:
# Named syntax is concise and yields readable column names.
dept_grp.agg(avg_salary = ('Salary', 'mean'), top_bonus = ('Bonus', 'max'))

      avg_salary  top_bonus
Dept
A      75.000000          8
B      66.666667          9