## Converting the datatype of a particular column.

In [72]:
import pandas as pd
import numpy as np

In [73]:
# Creating DataFrames using a dictionary
people = {
    "first": [
        "Ashish", "Corey", "John", "Meera", "Arjun",
        "Sophia", "Liam", "Hannah", "Carlos", "Jisoo"
    ],
    "last": [
        "Khanagwal", "Anderson", "Doe", "Patel", "Singh",
        "Williams", "Brown", "Nguyen", "Garcia", "Kim"
    ],
    "email_address": [
        "ashishkhanagwal@gmail.com",
        "coreyschafar@gmail.com",
        "timdavid@gmail.com",
        "meerapatel@gmail.com",
        "arjunsingh@gmail.com",
        "sophiawilliams@gmail.com",
        "liambrown@gmail.com",
        "hannahnguyen@gmail.com",
        "carlosgarcia@gmail.com",
        "jisookim@gmail.com"
    ],
    "age": [24, 27, 26, 25, 29, 31, 28, 24, 32, 26],
    "Profession": [
        "AI Engineer", "Tutor", "Software Developer", "Data Scientist", "Product Manager",
        "UX Designer", "DevOps Engineer", "Research Analyst", "Systems Architect", "ML Engineer"
    ],
    "Company": [
        "Meta", "YouTube", "Google", "Microsoft", "Amazon",
        "Apple", "Netflix", "Tesla", "IBM", "OpenAI"
    ],
    "Score": [85, 90, 88, 92, 89, 87, 91, 86, 93, 95]
}

In [74]:
df = pd.DataFrame(people)
df

,first,last,email_address,age,Profession,Company,Score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

### 1. Using .astype()
- This is the most common and easiest way.

In [75]:
df['age'] = df['age'].astype(str)
# This will covert data type of age from int to string.
df['age']

df['Score'] = df['Score'].astype(float)
# This will convert the data type of score from int to float.
df['Score']

0    85.0
1    90.0
2    88.0
3    92.0
4    89.0
5    87.0
6    91.0
7    86.0
8    93.0
9    95.0
Name: Score, dtype: float64

### 2. Using `pd.to_numeric()`, `pd.to_datetime()`, `pd.to_timedelta()`
- These are special functions for certain datatypes.

In [76]:
# To numbers (int/float):
df['age'] = pd.to_numeric(df['age'])
df['age']
# Converted from string to integer.

0    24
1    27
2    26
3    25
4    29
5    31
6    28
7    24
8    32
9    26
Name: age, dtype: int64

In [77]:
# To check data types of the dataframe.
df.dtypes

first             object
last              object
email_address     object
age                int64
Profession        object
Company           object
Score            float64
dtype: object

## Adding and Removing rows and columns
Adding and removing rows and columns in a pandas DataFrame is a common operation when preparing or cleaning up your data. Here’s how to do it in a clear, friendly way with practical examples:

## Adding Columns
Assign a new column by name:

In [78]:
df['full name'] = df['first'] + ' ' + df['last']

In [79]:
df

,first,last,email_address,age,Profession,Company,Score,full name
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim

## Removing Columns
Using drop:

In [80]:
df.drop(columns=['first', 'last'], inplace = True)
df
# This will remove the 'first' and 'last' columns from the dataframe.
# Removes the column “column_name” from the DataFrame. Use axis=1 for columns.

,email_address,age,Profession,Company,Score,full name
0,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal
1,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson
2,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe
3,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel
4,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh
5,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams
6,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown
7,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen
8,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia
9,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim

In [81]:
df['full name'].str.split(' ', expand = True)
# this is how full name column will be split into two seperate columns

        0          1
0  Ashish  Khanagwal
1   Corey   Anderson
2    John        Doe
3   Meera      Patel
4   Arjun      Singh
5  Sophia   Williams
6    Liam      Brown
7  Hannah     Nguyen
8  Carlos     Garcia
9   Jisoo        Kim

In [82]:
# Adding new columns and assigning value at the same time.
df[['first', 'last']] = df['full name'].str.split(' ', expand=True)
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim

## Adding Row

In [83]:
# New row as DataFrame, and other than 'fist' all values will be set to NaN.
new_row = pd.DataFrame({'first': ['Tony']})
df = pd.concat([df, new_row], ignore_index=True)

In [84]:
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
10,NaN,NaN,NaN,NaN,NaN,NaN,Tony,NaN

## Removing Rows
Drop rows by index:

In [85]:
df.drop(10, axis = 0, inplace=True)
# Removes the row with the specified index (use axis=0 for rows).

In [86]:
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim

# Drop multiple rows by index:
`df.drop([0, 2], axis=0, inplace=True)`

## Adding two DataFrames
### 1. Combine by Adding Rows (pd.concat)
Use case: You want one DataFrame under the other, with the same columns.

In [87]:
people = {
  'first': ['Tony', 'Steve'],
  'last' : ['Stark', 'Rogers'],
  'email_address': ['tonystark@avenge.com', 'steverogers@avenge.com']
}

df2 = pd.DataFrame(people)
df2

   first    last           email_address
0   Tony   Stark    tonystark@avenge.com
1  Steve  Rogers  steverogers@avenge.com

In [88]:
df = pd.concat([df, df2], ignore_index=True)
df

,email_address,age,Profession,Company,Score,full name,first,last
0,ashishkhanagwal@gmail.com,24.0,AI Engineer,Meta,85.0,Ashish Khanagwal,Ashish,Khanagwal
1,coreyschafar@gmail.com,27.0,Tutor,YouTube,90.0,Corey Anderson,Corey,Anderson
2,timdavid@gmail.com,26.0,Software Developer,Google,88.0,John Doe,John,Doe
3,meerapatel@gmail.com,25.0,Data Scientist,Microsoft,92.0,Meera Patel,Meera,Patel
4,arjunsingh@gmail.com,29.0,Product Manager,Amazon,89.0,Arjun Singh,Arjun,Singh
5,sophiawilliams@gmail.com,31.0,UX Designer,Apple,87.0,Sophia Williams,Sophia,Williams
6,liambrown@gmail.com,28.0,DevOps Engineer,Netflix,91.0,Liam Brown,Liam,Brown
7,hannahnguyen@gmail.com,24.0,Research Analyst,Tesla,86.0,Hannah Nguyen,Hannah,Nguyen
8,carlosgarcia@gmail.com,32.0,Systems Architect,IBM,93.0,Carlos Garcia,Carlos,Garcia
9,jisookim@gmail.com,26.0,ML Engineer,OpenAI,95.0,Jisoo Kim,Jisoo,Kim
10,tonystark@avenge.com,NaN,NaN,NaN,NaN,NaN,Tony,Stark
11,steverogers@avenge.com,NaN,NaN,NaN,NaN,NaN,Steve,Rogers