In [253]:
# Creating DataFrames using a dictionary
people = {
  "last": [
        "Khanagwal", "Anderson", "Doe", "Patel", "Singh",
        "Williams", "Brown", "Nguyen", "Garcia", "Kim"
    ],
    "first": [
        "Ashish", "Corey", "John", "Meera", "Arjun",
        "Sophia", "Liam", "Hannah", "Carlos", "Jisoo"
    ],
    "email_address": [
        "ashishkhanagwal@gmail.com",
        "coreyschafar@gmail.com",
        "timdavid@gmail.com",
        "meerapatel@gmail.com",
        "arjunsingh@gmail.com",
        "sophiawilliams@gmail.com",
        "liambrown@gmail.com",
        "hannahnguyen@gmail.com",
        "carlosgarcia@gmail.com",
        "jisookim@gmail.com"
    ],
    "age": [24, 27, 26, 25, 29, 31, 28, 24, 32, 26],
    "Profession": [
        "AI Engineer", "Tutor", "Software Developer", "Data Scientist", "Product Manager",
        "UX Designer", "DevOps Engineer", "Research Analyst", "Systems Architect", "ML Engineer"
    ],
    "Company": [
        "Meta", "YouTube", "Google", "Microsoft", "Amazon",
        "Apple", "Netflix", "Tesla", "IBM", "OpenAI"
    ],
    "Score": [85, 90, 88, 92, 89, 87, 91, 86, 93, 95]
}

In [254]:
import pandas as pd

df = pd.DataFrame(people)
df
# This is how we make dataframe using a dictionary.

,last,first,email_address,age,Profession,Company,Score
0,Khanagwal,Ashish,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Anderson,Corey,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,Doe,John,timdavid@gmail.com,26,Software Developer,Google,88
3,Patel,Meera,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Singh,Arjun,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Williams,Sophia,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Brown,Liam,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Nguyen,Hannah,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Garcia,Carlos,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Kim,Jisoo,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [255]:
df['email_address'] # Or df.email

0    ashishkhanagwal@gmail.com
1       coreyschafar@gmail.com
2           timdavid@gmail.com
3         meerapatel@gmail.com
4         arjunsingh@gmail.com
5     sophiawilliams@gmail.com
6          liambrown@gmail.com
7       hannahnguyen@gmail.com
8       carlosgarcia@gmail.com
9           jisookim@gmail.com
Name: email_address, dtype: object

In [256]:
type(df['email_address'])

pandas.core.series.Series

## A Series in pandas is best understood as a single column of labeled data, like one list or array in a spreadsheet.

### Beginner-Friendly Explanation
- Imagine a Series as a vertical list of data values, each with a label called the index.
- Each value in the Series can be a number, string, or other type, and every value has a unique position or index on the left side, like row numbers in Excel.
- For example, if you have survey answers or ages, those could be stored in a Series.

### Key Points:
- A Series is simpler than a DataFrame; it contains data in just one column but with many rows.
- You can access items using their position (like series) or their label (like series['Alice']).
- Series makes it easy to analyze, process, and manipulate one set of data at a time.

Series is the foundation for columns in a DataFrame. Whenever you select a single column from a DataFrame, you get a Series. This makes Series crucial for all kinds of fast, efficient, and beginner-friendly data operations.

In [257]:
df[['first', 'last']]

    first       last
0  Ashish  Khanagwal
1   Corey   Anderson
2    John        Doe
3   Meera      Patel
4   Arjun      Singh
5  Sophia   Williams
6    Liam      Brown
7  Hannah     Nguyen
8  Carlos     Garcia
9   Jisoo        Kim

In [258]:
df.columns

Index(['last', 'first', 'email_address', 'age', 'Profession', 'Company',
       'Score'],
      dtype='object')

In [259]:
df.iloc[[0, 2]]

,last,first,email_address,age,Profession,Company,Score
0,Khanagwal,Ashish,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
2,Doe,John,timdavid@gmail.com,26,Software Developer,Google,88

In [260]:
df.loc[[0, 1], ['last', 'email_address']]

        last              email_address
0  Khanagwal  ashishkhanagwal@gmail.com
1   Anderson     coreyschafar@gmail.com

#### The main difference between df.loc and df.iloc in pandas is how you select rows and columns—by label or by position.

### `df.loc`: Label-Based Indexing
- `df.loc` is used to access data by row and column labels (names).
- If your DataFrame has custom indexes like names or specific labels, you use those with `loc`.
- Slicing with `.loc` is inclusive of the end label.

Example:
```
df.loc['B', 'Age']      # Selects the row with label 'B' and column 'Age'
df.loc['A':'C']         # Selects rows from label 'A' to 'C' (inclusive)
```

### `df.iloc`: Integer-Based Indexing
- `df.iloc` is used to access data by row and column positions, using integer indices (like you would with a Python list).
- The first row and column are at position 0, the second at 1, and so on.
- Slicing with `.iloc` is exclusive of the end index, just like standard Python lists.

Example:
```
df.iloc[1, 1]           # Selects the second row and second column (both index 1)
df.iloc[0:2]            # Selects rows at positions 0 and 1 (end excluded)
```

##### Indexes in pandas are labels for rows that help organize, access, and manage DataFrames efficiently. Here’s a beginner-friendly, in-depth guide with practical examples:

### Understanding Indexes
- By default, every DataFrame row gets an index starting from 0, 1, 2, etc. This is helpful for referencing rows.
- Indexes can be changed to use meaningful labels, like names or dates, making data easier to work with.

### Setting an Index
- Use `df.set_index('ColumnName')` to make a column the index. The original row numbers are replaced by those values.

- You can also set multiple columns as a "MultiIndex" using a list: `df.set_index(['Name', 'Age'])`

In [261]:
df.set_index('last', inplace = True)
df

,first,email_address,age,Profession,Company,Score
last,,,,,,
Khanagwal,Ashish,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
Anderson,Corey,coreyschafar@gmail.com,27,Tutor,YouTube,90
Doe,John,timdavid@gmail.com,26,Software Developer,Google,88
Patel,Meera,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
Singh,Arjun,arjunsingh@gmail.com,29,Product Manager,Amazon,89
Williams,Sophia,sophiawilliams@gmail.com,31,UX Designer,Apple,87
Brown,Liam,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
Nguyen,Hannah,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
Garcia,Carlos,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
Kim,Jisoo,jisookim@gmail.com,26,ML Engineer,OpenAI,95

### Resetting an Index
- To restore the default numeric index, use df.reset_index(), which puts the current index back as a column and re-numbers rows from zero.

```
df_reset = df.reset_index()
print(df_reset)
```

- If you want to discard the old index, use `df.reset_index(drop=True)`.
- You can do this in place with inplace=True: `df.reset_index(inplace=True)`

In [262]:
df.reset_index(inplace = True)
df

,last,first,email_address,age,Profession,Company,Score
0,Khanagwal,Ashish,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Anderson,Corey,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,Doe,John,timdavid@gmail.com,26,Software Developer,Google,88
3,Patel,Meera,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Singh,Arjun,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Williams,Sophia,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Brown,Liam,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Nguyen,Hannah,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Garcia,Carlos,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Kim,Jisoo,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [263]:
df.set_index('first', inplace= True)

In [264]:
df.reset_index(inplace=True)

| Operation                |  Code Example                        |  What it Does                       
| :-------------------------:|:--------------------------------------:|:-------------------------------------:|
| Set index                |  df.set_index('Name', inplace=True)  |  Uses the 'Name' column as row index|
| Reset index              |  df.reset_index(inplace=True)        |  Returns to default integer index   |
| Drop old index on reset  |  df.reset_index(drop=True)           |  Removes index, starts at zero      |
| Access index labels      |  df.index                            |  Returns row labels                 |
| Assign custom index      |  df.index = ['a','b','c']            |  Sets new labels for rows           |

#### Filtering data in pandas means choosing the rows or columns that match specific conditions. This helps zoom in on the information most relevant to your task.

In [265]:
filt = df['last'] == 'Khanagwal'
df[filt] 

# Above can also be written as:
# df[df['last'] == 'Khanagwal']

,first,last,email_address,age,Profession,Company,Score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85

In [266]:
df.loc[filt, 'email_address']

0    ashishkhanagwal@gmail.com
Name: email_address, dtype: object

In [267]:
# Filtering Rows with Conditionals
# The basic way is using Boolean indexing:
df[df['age'] > 24]

,first,last,email_address,age,Profession,Company,Score
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

- This keeps only rows where the “Age” column is greater than 30.

#### You can filter by multiple conditions using logical operators:
- & means “and”
- | means “or”

In [268]:
filtered_df = (df['last'] == 'Khanagwal') & (df['age'] > 20)
df.loc[filtered_df]

,first,last,email_address,age,Profession,Company,Score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85

In [269]:
filter_df = (df['last'] == 'Khanagwal') | (df['first'] == 'Corey')
df.loc[filter_df]

,first,last,email_address,age,Profession,Company,Score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90

In [270]:
f = (df['last'] == 'Khanagwal') | (df['first'] == 'Corey')
df.loc[~f] 
# This will give us the row which has last and first other than 'Khanagwal' and 'Corey' respectively.

,first,last,email_address,age,Profession,Company,Score
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

#### Updating rows and columns in pandas is simple and powerful, letting you directly modify, overwrite, or transform data in a DataFrame.

In [271]:
df.columns

Index(['first', 'last', 'email_address', 'age', 'Profession', 'Company',
       'Score'],
      dtype='object')

In [272]:
# one way to change column name
df.columns = ['first name', 'last name', 'email address', 'age', 'profession', 'company', 'score']
df.columns

Index(['first name', 'last name', 'email address', 'age', 'profession',
       'company', 'score'],
      dtype='object')

In [273]:
df.columns = [x.upper() for x in df.columns]
# List comprehension helps us to change name of columns
df

,FIRST NAME,LAST NAME,EMAIL ADDRESS,AGE,PROFESSION,COMPANY,SCORE
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [274]:
df.columns = df.columns.str.replace(' ', '_')
# It will replace the ' ' between the strings with '_'
df

,FIRST_NAME,LAST_NAME,EMAIL_ADDRESS,AGE,PROFESSION,COMPANY,SCORE
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [275]:
df.columns = [x.lower() for x in df.columns]
df

,first_name,last_name,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [276]:
df.rename(columns={'first_name': 'first', 'last_name':'last'}, inplace = True)
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,Software Developer,Google,88
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

### Updating Rows
- Entire Row: Assign a new row with a list or dict via .loc.

In [277]:
df.loc[2] = ['Tim', 'David', 'timdavid@gmail.com', 26, 'App Developer', 'Flipkart', '89']
df
# This will update the entire 2nd row.

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_18604/661296542.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '89' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[2] = ['Tim', 'David', 'timdavid@gmail.com', 26, 'App Developer', 'Flipkart', '89']

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,Tim,David,timdavid@gmail.com,26,App Developer,Flipkart,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [278]:
# In order to update the specific element we do like this:
df.loc[2, ['last', 'first']] = ['Doe', 'John']
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,App Developer,Flipkart,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [279]:
# df['Profession'] = ['AI Engineer', 'Tuttor', 'Software Developer']
# df['Company'] = ['Meta', 'Youtube', 'Google']
# df['Score'] = [85, 90, 88]
# df

#### Single Cell: Use .at (by label) or .iat (by position) to update one specific value.

In [280]:
df.at[1, 'last'] = 'Anderson'
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,App Developer,Flipkart,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

## 1. What .loc does
- .loc is like a Swiss army knife — it can select:
  - single cells
  - entire rows
  - entire columns
  - a block of rows and columns

#### So when you do something like:

```
df.loc[2, 'Score'] = 95
```

- it will work — pandas will update that one cell.
- But behind the scenes, pandas first checks: "Am I selecting one value, or a slice of the DataFrame?"
That checking makes `.loc` a bit slower for single-cell updates.

## 2. What .at does
- .at is specialized: it is made only for getting or setting a single cell (scalar).
```
df.at[2, 'Score'] = 95
```

- Here, pandas knows right away:

👉 "Oh, this is just one specific cell. No need to check for slices or ranges."

#### That makes `.at`:
- faster
- clearer in intention (other programmers immediately know you’re working with one single value, not a row or slice)

In [281]:
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,26,App Developer,Flipkart,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [282]:
df.iat[2, 3] = 28
# 2nd row, and 3rd column -> Age of John
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,John,Doe,timdavid@gmail.com,28,App Developer,Flipkart,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [283]:
df.iloc[2, [0, 1, 3, 5]] = ["Johny", "Bairstow", 30, 'Amazon']
df

,first,last,email_address,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal@gmail.com,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,Johny,Bairstow,timdavid@gmail.com,30,App Developer,Amazon,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

### 🔑 Quick Summary:
- .at → label-based, fast for single cell.
- .iat → position-based, fast for single cell.
- .loc → label-based, flexible (rows, slices, cells, multiple).
- .iloc → position-based, flexible (rows, slices, cells, multiple).

## Difference between label based and position based:

#### `df.iloc[1, ['last', 'age', 'Company']]` -> Says (TypeError: Cannot index by location index with a non-integer key) 
## Why above `.iloc` code failed?
- `.iloc` is position-based only (integer row & column positions).
- But here, you gave it `['last', 'age', 'Company']`, which are column labels (strings).
- That’s why pandas complains:
“Cannot index by location index with a non-integer key”

#### `df.loc[1, ['last', 'age', 'Company']]` -> This will work as expected.
## Why `.loc` works
- `.loc` is label-based.
- You’re using 1 (row label) and `['last', 'age', 'Company']` (column labels).
- That matches perfectly → so pandas updates the row as expected.

In [284]:
df.rename(columns = {'email_address': 'email'}, inplace = True)
filt = (df['email'] == 'ashishkhanagwal@gmail.com')
df.loc[filt, 'email'] = 'ashishkhanagwal2001@gmail.comm'
df

,first,last,email,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal2001@gmail.comm,24,AI Engineer,Meta,85
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,90
2,Johny,Bairstow,timdavid@gmail.com,30,App Developer,Amazon,89
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,92
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,89
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,87
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,91
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,86
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,93
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,95

In [285]:
df['score'] = pd.to_numeric(df['score'])
df['score'] = df['score'] + 3
df['score']

0    88
1    93
2    92
3    95
4    92
5    90
6    94
7    89
8    96
9    98
Name: score, dtype: int64

### 1. apply: Row/Column-wise Operations
- Purpose: Used for applying a function to each row or column of a DataFrame, or to each value in a Series.
- How it works: It processes one entire row or column at a time.

In [286]:
df['email'].apply(len)

0    30
1    22
2    18
3    20
4    20
5    24
6    19
7    22
8    22
9    18
Name: email, dtype: int64

In [287]:
def upper_email(email):
  return email.upper()

df['email'] = df['email'].apply(upper_email)
df

,first,last,email,age,profession,company,score
0,Ashish,Khanagwal,ASHISHKHANAGWAL2001@GMAIL.COMM,24,AI Engineer,Meta,88
1,Corey,Anderson,COREYSCHAFAR@GMAIL.COM,27,Tutor,YouTube,93
2,Johny,Bairstow,TIMDAVID@GMAIL.COM,30,App Developer,Amazon,92
3,Meera,Patel,MEERAPATEL@GMAIL.COM,25,Data Scientist,Microsoft,95
4,Arjun,Singh,ARJUNSINGH@GMAIL.COM,29,Product Manager,Amazon,92
5,Sophia,Williams,SOPHIAWILLIAMS@GMAIL.COM,31,UX Designer,Apple,90
6,Liam,Brown,LIAMBROWN@GMAIL.COM,28,DevOps Engineer,Netflix,94
7,Hannah,Nguyen,HANNAHNGUYEN@GMAIL.COM,24,Research Analyst,Tesla,89
8,Carlos,Garcia,CARLOSGARCIA@GMAIL.COM,32,Systems Architect,IBM,96
9,Jisoo,Kim,JISOOKIM@GMAIL.COM,26,ML Engineer,OpenAI,98

In [288]:
df['email'] = df['email'].apply(lambda x: x.lower())
df

,first,last,email,age,profession,company,score
0,Ashish,Khanagwal,ashishkhanagwal2001@gmail.comm,24,AI Engineer,Meta,88
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,93
2,Johny,Bairstow,timdavid@gmail.com,30,App Developer,Amazon,92
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,95
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,92
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,90
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,94
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,89
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,96
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,98

In [289]:
df['Status'] = df['score'].apply(lambda x: 'Pass' if x > 90 else 'Fail')
df
# Update with a Formula or Function: Apply math operations or functions to update all values.

,first,last,email,age,profession,company,score,Status
0,Ashish,Khanagwal,ashishkhanagwal2001@gmail.comm,24,AI Engineer,Meta,88,Fail
1,Corey,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,93,Pass
2,Johny,Bairstow,timdavid@gmail.com,30,App Developer,Amazon,92,Pass
3,Meera,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,95,Pass
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,92,Pass
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,90,Fail
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,94,Pass
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,89,Fail
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,96,Pass
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,98,Pass

In [290]:
# This is how apply works on dataframe
df.apply(len)
# Actually, this is telling is the length each label (how many values stored).

first         10
last          10
email         10
age           10
profession    10
company       10
score         10
Status        10
dtype: int64

In [291]:
df.apply(len, axis=1)
# And this is telling us the number of elements stored in each row.

0    8
1    8
2    8
3    8
4    8
5    8
6    8
7    8
8    8
9    8
dtype: int64

In [292]:
df.apply(pd.Series.min)
# This will give the smallest values in the whole dataframe from all series.

first                        Arjun
last                      Anderson
email         arjunsingh@gmail.com
age                             24
profession             AI Engineer
company                     Amazon
score                           88
Status                        Fail
dtype: object

#### `DataFrame.apply(func, axis=0)` → applies func column by column (default axis=0).
#### `DataFrame.apply(func, axis=1)` → applies func row by row.

In [293]:
df.apply(lambda x: x.max())
# Because of above logic, that's why here 'x' refer to series.

first                     Sophia
last                    Williams
email         timdavid@gmail.com
age                           32
profession           UX Designer
company                  YouTube
score                         98
Status                      Pass
dtype: object

#### running apply to a series, applies a functions to every value in the series.
#### running apply to a dataframe, applies the function to every series in the dataframe.

### 2. applymap: Element-wise on DataFrame
- Purpose: Used for applying a function to every single value in an entire DataFrame.
- How it works: Processes independently over all DataFrame cells.

In [294]:
df[['age', 'score']] = df[['age', 'score']].apply(pd.to_numeric)

In [295]:
lengths = df.applymap(lambda x: len(x) if isinstance(x, str) else None)
lengths

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_18604/677992431.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lengths = df.applymap(lambda x: len(x) if isinstance(x, str) else None)

   first  last  email   age  profession  company score  Status
0      6     9     30  None          11        4  None       4
1      5     8     22  None           5        7  None       4
2      5     8     18  None          13        6  None       4
3      5     5     20  None          14        9  None       4
4      5     5     20  None          15        6  None       4
5      6     8     24  None          11        5  None       4
6      4     5     19  None          15        7  None       4
7      6     6     22  None          16        5  None       4
8      6     6     22  None          17        3  None       4
9      5     3     18  None          11        6  None       4

In [296]:
lowered = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)
lowered

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_18604/3078225886.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  lowered = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

,first,last,email,age,profession,company,score,Status
0,ashish,khanagwal,ashishkhanagwal2001@gmail.comm,24,ai engineer,meta,88,fail
1,corey,anderson,coreyschafar@gmail.com,27,tutor,youtube,93,pass
2,johny,bairstow,timdavid@gmail.com,30,app developer,amazon,92,pass
3,meera,patel,meerapatel@gmail.com,25,data scientist,microsoft,95,pass
4,arjun,singh,arjunsingh@gmail.com,29,product manager,amazon,92,pass
5,sophia,williams,sophiawilliams@gmail.com,31,ux designer,apple,90,fail
6,liam,brown,liambrown@gmail.com,28,devops engineer,netflix,94,pass
7,hannah,nguyen,hannahnguyen@gmail.com,24,research analyst,tesla,89,fail
8,carlos,garcia,carlosgarcia@gmail.com,32,systems architect,ibm,96,pass
9,jisoo,kim,jisookim@gmail.com,26,ml engineer,openai,98,pass

### 3. map: Element-wise on Series
- Purpose: Used for transforming/formatting each individual value in a pandas Series (single column).
- How it works: Applies a function, dictionary, or mapping to each item in a Series.

In [301]:
df['first'].map({'Corey': 'Mitchel', 'Meera': 'shruti'})

# Here, other than the values I updated are all NaN and we certainly don't want that, that is why we use replace.

0        NaN
1    Mitchel
2        NaN
3     shruti
4        NaN
5        NaN
6        NaN
7        NaN
8        NaN
9        NaN
Name: first, dtype: object

### 4. replace: Substituting Values
- Purpose: Quickly substitute specified values in a Series or DataFrame.
- How it works: Finds values and replaces them according to the input mapping.

Example (Single Value):

In [304]:
df['first'] = df['first'].replace({'Corey': 'Mitchel', 'Meera': 'shruti'})
df

# And here, everything works perfectly fine.

,first,last,email,age,profession,company,score,Status
0,Ashish,Khanagwal,ashishkhanagwal2001@gmail.comm,24,AI Engineer,Meta,88,Fail
1,Mitchel,Anderson,coreyschafar@gmail.com,27,Tutor,YouTube,93,Pass
2,Johny,Bairstow,timdavid@gmail.com,30,App Developer,Amazon,92,Pass
3,shruti,Patel,meerapatel@gmail.com,25,Data Scientist,Microsoft,95,Pass
4,Arjun,Singh,arjunsingh@gmail.com,29,Product Manager,Amazon,92,Pass
5,Sophia,Williams,sophiawilliams@gmail.com,31,UX Designer,Apple,90,Fail
6,Liam,Brown,liambrown@gmail.com,28,DevOps Engineer,Netflix,94,Pass
7,Hannah,Nguyen,hannahnguyen@gmail.com,24,Research Analyst,Tesla,89,Fail
8,Carlos,Garcia,carlosgarcia@gmail.com,32,Systems Architect,IBM,96,Pass
9,Jisoo,Kim,jisookim@gmail.com,26,ML Engineer,OpenAI,98,Pass