In [217]:
import numpy as np
import pandas as pd

In [218]:
df = pd.read_csv('data/words.csv', index_col='Word')

In [219]:
df.head()

      Value  Char Count
Word
the     207           3
and     398           3
of      225           2
to       30           2
a       142           1

# Activities

#### How many elements does this dataframe have?

In [220]:
df.shape

(102, 2)

In [221]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102 entries, the to ultramicrospectrophotometries
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Value       102 non-null    int64
 1   Char Count  102 non-null    int64
dtypes: int64(2)
memory usage: 2.4+ KB

#### What is the value of microspectrophotometries?

In [222]:
df.loc['microspectrophotometries']['Value']

np.int64(193)

#### What is the highest possibel value of a word?
- There are multiple methods for it, see below

In [223]:
df.max()

Value         398
Char Count     35
dtype: int64

In [224]:
df['Value'].max()

np.int64(398)

In [225]:
df.describe()

            Value  Char Count
count  102.000000  102.000000
mean   205.372549   18.382353
std    106.391387    6.368307
min     10.000000    1.000000
25%    120.250000   17.000000
50%    200.000000   19.000000
75%    291.500000   21.000000
max    398.000000   35.000000

In [226]:
filt = (df['Value'] == 236) | (df['Char Count'] == 17)
df.loc[filt]

# Another way of doing it:-
# df.loc[(df['Value'] == 236) | (df['Char Count'] == 17)]

                   Value  Char Count
Word
conceptualization    318          17
thermodynamically    383          17
microbiologically    360          17
incompatibilities    171          17
misappropriations    337          17
extraordinariness    236          17
interdisciplinary     57          17
counterproductive    373          17
contradistinguish    134          17

#### What is the highest possible length of a word?

In [227]:
df['Char Count'].max()

np.int64(35)

#### What is the word with the value of 232?

In [228]:
df.loc[(df['Value'] == 232)]

                    Value  Char Count
Word
overgeneralization    232          18

#### What is the most common value?

In [229]:
# Sorting
df.sort_values(by=['Value'], ascending=False)

                        Value  Char Count
Word
and                       398           3
electroencephalographs    396          22
thermodynamically         383          17
photosensitization        383          18
neuropsychological        378          18
...                       ...         ...
anthropomorphization       42          20
biotechnological           41          16
to                         30           2
unconstitutionality        17          19
bioinstrumentation         10          18

[102 rows x 2 columns]

In [230]:
most_common_value = df['Value'].mode()[0]
count = df['Value'].value_counts()[most_common_value]
most_common_value

np.int64(290)

### Explanation:
- #### df['Value'].mode() returns the value(s) that appear most frequently.
- #### df['Value'].value_counts() counts the occurrences of each value.
- #### [0] selects the first mode if there are multiple.

In [231]:
words_most_common_value = df[df['Value'] == most_common_value].index.tolist()
words_most_common_value

['multidimensional', 'counterproductivenesses', 'microphotolithographies']

#### Why we did `.index`?
Our DataFrame has 'Word' as the index. When a column is the index, it is not available as a normal column, so doing 'df['Word']' will fail. And we get the error.

Instead, you should use the index itself.
- `words_most_common_value = df[df['Value'] == most_common_value].index.tolist()`

#### .tolist()
- Converts the resulting Series (the 'Word' column) into a Python list.
- So you get a simple list of words that have the most common value.

| Original line                                           | Why it fails                              | Correct approach                                      |
| :-------------------------------------------------------: | :-----------------------------------------: | :-----------------------------------------------------: |
| `df[df['Value'] == most_common_value]['Word'].tolist()` | `'Word'` is not a column (it’s the index) | `df[df['Value'] == most_common_value].index.tolist()` |

In [232]:
df.loc[df['Value'] == 290].sample(3)

                         Value  Char Count
Word
multidimensional           290          16
microphotolithographies    290          23
counterproductivenesses    290          23

#### What is the shortest word with the value 290?

In [233]:
# Most common value
most_common_value = df['Value'].mode()[0]

# Minimum Char Count among words with most common value
min_char_count = df[df['Value'] == most_common_value]['Char Count'].min()

# Filter rows with that Value and Char Count
shortest_word = df[(df['Value'] == most_common_value) & (df['Char Count'] == min_char_count)].index[0]
shortest_word

'multidimensional'

#### Create a column Ratio which represents the 'Value Ratio' of a word

##### The "Value Ratio" of a word is defined as the Value of a word divided by its length. That is: ValueRatio(word) = Value(word) / len(word).

- Create a new column in your DataFrame named Ratio that contains such computation.

In [234]:
df['Value Ratio'] = df['Value'] / df['Char Count']
df

                               Value  Char Count  Value Ratio
Word
the                              207           3    69.000000
and                              398           3   132.666667
of                               225           2   112.500000
to                                30           2    15.000000
a                                142           1   142.000000
...                              ...         ...          ...
psychopharmacologically          304          23    13.217391
electrophotographically          133          23     5.782609
counterdemonstrational           158          22     7.181818
psychophysiologically            104          21     4.952381
ultramicrospectrophotometries    106          29     3.655172

[102 rows x 3 columns]

#### What is the maximum value of ratio?

In [235]:
df['Value Ratio'].max()

np.float64(142.0)

#### What word is the one with the highest ratio?

In [236]:
highest_ratio = df['Value Ratio'].max()
word_highest_ratio = df[df['Value Ratio'] == highest_ratio].index[0]
word_highest_ratio

'a'

#### How many words with a ratio of 6?

In [237]:
df['Value Ratio'].value_counts()

Value Ratio
6.000000     5
12.608696    2
69.000000    1
2.100000     1
3.111111     1
            ..
21.176471    1
3.615385     1
22.529412    1
2.857143     1
3.655172     1
Name: count, Length: 97, dtype: int64

In [238]:
most_common_ratio = df['Value Ratio'].mode()
words_common_ratio = df[df['Value Ratio'] == most_common_ratio].index.tolist()
words_common_ratio

ValueError: Can only compare identically-labeled Series objects

## 🔎 Why mode() caused an error and how to fix it
### My approach (why it failed)
```
most_common_ratio = df['Value Ratio'].mode()
words_common_ratio = df[df['Value Ratio'] == most_common_ratio].index.tolist()
```

- `df['Value Ratio'].mode()` returns a Series, not a single value.
 > 6.0    5

- When you do df['Value Ratio'] == most_common_ratio, you’re comparing:
  - `df['Value Ratio']` → a Series with as many rows as your DataFrame
  - `most_common_ratio` → a Series with just one row (index = 0)
- Pandas requires Series objects being compared to have the same index labels. Since they don’t match, you get:

`ValueError: Can only compare identically-labeled Series objects`

### Correct approach (why it works)
```
most_common_ratio = df['Value Ratio'].mode().iloc[0]
words_common_ratio = df[df['Value Ratio'] == most_common_ratio].index.tolist()
```
- `.iloc[0]` extracts the first element from the mode Series, giving you a scalar value (e.g., 10.0) instead of a Series.
- Now you are comparing:
  - `df['Value Ratio']` → Series of ratios
  - `most_common_ratio` → single scalar value
- This comparison works fine, and Pandas returns a Boolean mask where each row is checked against the scalar.
- The filter then selects all rows with that ratio, and `.index.tolist()` gives you the words.


| Approach                      | What it returns                       | Why it fails/works                                 |
| :-----------------------------: | :-------------------------------------: | :--------------------------------------------------: |
| `mode()` (your code)          | A **Series** (even if only one value) | Can’t compare Series with different labels → error |
| `mode().iloc[0]` (fixed code) | A **scalar** (single number)          | Scalar comparison works with Series → valid mask   |

In [239]:
most_common_ratio = df['Value Ratio'].mode().iloc[0]
words_common_ratio = df[df['Value Ratio'] == most_common_ratio].index.tolist()
words_common_ratio

['virtualization',
 'capitalization',
 'interpretation',
 'reconceptualization',
 'counterdemonstrator']

In [240]:
df.query('`Value Ratio` == 6')

                     Value  Char Count  Value Ratio
Word
virtualization         108          18          6.0
capitalization         120          20          6.0
interpretation         126          21          6.0
reconceptualization    114          19          6.0
counterdemonstrator    114          19          6.0

### 🔎 What it does:
- `.query()` lets you filter a DataFrame using a string expression instead of the usual Boolean mask.
- Inside the string, you can write conditions almost like plain Python.

So this line means:
👉 “Give me all rows where the column Value Ratio is equal to 6.”

##### Since your column name has a space ("Value Ratio"), Pandas normally expects you to use backticks around it:
```df.query('`Value Ratio` == 6')```

Without backticks, Pandas may get confused and throw an error like:

`UndefinedVariableError: name 'Value' is not defined`

```
# works if no spaces in column name
df.query('Value == 290')

# correct way when column has spaces
df.query('`Value Ratio` == 6')

# multiple conditions
df.query('`Value Ratio` == 6 and Char Count > 10')
```

In [241]:
df.query('`Value Ratio` == 6').shape

(5, 3)

#### What is the maximum value of all the words with a Ratio of 6?

In [243]:
# One Way
df.query('`Value Ratio` == 6').sort_values(by='Value', ascending=False).head()

                     Value  Char Count  Value Ratio
Word
interpretation         126          21          6.0
capitalization         120          20          6.0
reconceptualization    114          19          6.0
counterdemonstrator    114          19          6.0
virtualization         108          18          6.0

In [245]:
# Other Way
df.loc[df['Value Ratio'] == 6, 'Value'].max()

np.int64(126)

#### Of those words with a value of 290, what is the lowest char count found?

In [258]:
df.query('Value == 290').sort_values(by='Char Count')

                         Value  Char Count  Value Ratio
Word
multidimensional           290          16    18.125000
counterproductivenesses    290          23    12.608696
microphotolithographies    290          23    12.608696

#### Based on previous task, what word it is?

In [271]:
min_char_count = df[(df['Value'] == 290)]['Char Count'].min()
min_char_count_word = df[(df['Char Count'] == min_char_count) & (df['Value'] == 290)].index[0]
min_char_count_word

'multidimensional'