# Birthday Problem Probability
The focus of this quick project is to put your Data Analysis with Pandas Skills to a test.

We're going to be analyzing the "Birthday Paradox" using data from the NBA.

In particular, the Birthday Paradox refers to the counterintuitive fact that only 23 people are needed for the probability of two people having a birthday on the same day, exceeds 50%.

This project will deal, not only with Pandas skills, but also with Probability concepts and combinatorics.

In [237]:
import pandas as pd
import numpy as np
import math

In [238]:
df = pd.read_csv('data/nba.csv')
pd.set_option('display.max_columns', 29)

In [239]:
# Adding a new column Birth Date and adding random dates.

from datetime import datetime, timedelta

start_date = datetime.strptime('1985-01-01', '%Y-%m-%d')
end_date = datetime.strptime('2000-12-31', '%Y-%m-%d')

def random_dates(n, start, end):
    delta = end - start
    return [start + timedelta(days=np.random.randint(0, delta.days)) for _ in range(n)]

df['Birth Date'] = random_dates(len(df), start_date, end_date)

# Save to a new CSV
df.to_csv('data/nba.csv', index=False)

In [240]:
# Deleting all the other columns and keeping only mentioned below.

df = df[['Player', 'Age', 'Pos', 'Birth Date']]

# Save back to the same CSV, overwriting it
df.to_csv('data/nba.csv', index=False)

In [241]:
team_df = pd.read_csv('data/nba_team.csv')
team_df.shape

(664, 2)

In [242]:
# Adding Team column from the nba_team.csv to nba.csv

team_df = team_df[['Team']]
if len(df) != len(team_df):
    print("Warning: Number of players and number of teams do not match!")
df['Team'] = team_df['Team']
df.to_csv('data/nba.csv', index=False)

In [243]:
# Deleting "*" from the end of the team name

df['Team'] = df['Team'].str.rstrip('*')
df['Player'] = df['Player'].str.split('\\').str[0]
df.to_csv('data/nba.csv', index=False)

In [244]:
df.head()

          Player  Age Pos Birth Date              Team
0   Alex Abrines   24  SG 1987-10-18  Sacramento Kings
1     Quincy Acy   27  PF 1993-04-13   Detroit Pistons
2   Steven Adams   24   C 1996-09-18  Dallas Mavericks
3    Bam Adebayo   20   C 1987-11-27    Indiana Pacers
4  Arron Afflalo   32  SG 1990-10-16   Milwaukee Bucks

In [245]:
df['Team'].value_counts()

Team
Sacramento Kings                     22
Denver Nuggets                       22
Los Angeles Clippers                 22
Atlanta Hawks                        22
Philadelphia 76ers                   22
Golden State Warriors                22
Utah Jazz                            22
Portland Trail Blazers               22
Minnesota Timberwolves               22
Phoenix Suns                         22
Washington Wizards                   22
Indiana Pacers                       22
Dallas Mavericks                     22
Boston Celtics                       22
Milwaukee Bucks                      22
San Antonio Spurs                    21
League Average                       21
Chicago Bulls                        21
New York Knicks                      21
Miami Heat                           21
Los Angeles Lakers                   21
Orlando Magic                        21
Detroit Pistons                      21
Cleveland Cavaliers                  21
Toronto Raptors                      21
Houston Rockets                      21
Memphis Grizzlies                    20
New Jersey Nets                      13
Oklahoma City Thunder                12
Charlotte Bobcats                    10
Brooklyn Nets                         9
Seattle SuperSonics                   9
New Orleans Hornets                   9
Charlotte Hornets                     9
New Orleans Pelicans                  8
New Orleans/Oklahoma City Hornets     2
Vancouver Grizzlies                   2
Name: count, dtype: int64

## Birthday Probelm Probability
#### [Birthday Probability Problem](https://en.wikipedia.org/wiki/Birthday_problem)

##### The first step will be to calculate the probability of two people sharing a birthday, in a group of n people. We can use the following approximation formula:

![Birthday Probability Formuale](birthday-probability.png "Birthday Probability Formuale")

In [246]:
def nCr(n ,k):
  f = math.factorial
  return f(n) / (f(k) * f( n - k))

In [247]:
nCr(5, 2)

10.0

In [248]:
nCr(6, 2)

15.0

## Activity: Implement the birthday probabilty function.

#### 1. What's the probability when n = 10?

What's the (approximate) probability of two people sharing a birthday in a group of 10 people?

Important: Enter the first two decimals. Example, if the result is 0.0982, enter 0.09. If it's 0.1012, enter 0.10. Don't round-off the answer.

In [249]:
1 - (364 / 365) ** nCr(10, 2)

0.11614023654879224

#### 2. What's the probability when n = 15?

In [250]:
1 - (364 / 365) ** nCr(15, 2)

0.25028790861398265

#### 3. Write the function birthday_probability

Now it's time to generalize the probability calculation and create the function `birthday_probability` that returns the probability of two people sharing a birthday when in a group of `number_of_people`.

In [251]:
def birthday_probability(number_of_people):
  return 1 - (364 / 365) ** nCr(number_of_people, 2)

In [252]:
birthday_probability(10)

0.11614023654879224

In [253]:
birthday_probability(15)

0.25028790861398265

## Data Preparation & Combinatorics
Before we're able to answer questions about shared birthdays, we need to do some data preparation.

#### 4. Create the column Birthday in the df

Use the column `Birth Date` to extract the "Birthday" (just Month and Day) for each player in the format `MM-DD`. Example: `08-01` is August, 1st.

You can use the `df['Birth Date'].dt.strftime` method, which accepts a "formatting template" which you can use to decide the formatting of the date. Refer to the docs for more details.

In [254]:
df.head()

          Player  Age Pos Birth Date              Team
0   Alex Abrines   24  SG 1987-10-18  Sacramento Kings
1     Quincy Acy   27  PF 1993-04-13   Detroit Pistons
2   Steven Adams   24   C 1996-09-18  Dallas Mavericks
3    Bam Adebayo   20   C 1987-11-27    Indiana Pacers
4  Arron Afflalo   32  SG 1990-10-16   Milwaukee Bucks

In [255]:
df.shape

(664, 5)

In [256]:
df['Birthday'] = df['Birth Date'].dt.strftime("%m-%d")

In [257]:
df.head()

          Player  Age Pos Birth Date              Team Birthday
0   Alex Abrines   24  SG 1987-10-18  Sacramento Kings    10-18
1     Quincy Acy   27  PF 1993-04-13   Detroit Pistons    04-13
2   Steven Adams   24   C 1996-09-18  Dallas Mavericks    09-18
3    Bam Adebayo   20   C 1987-11-27    Indiana Pacers    11-27
4  Arron Afflalo   32  SG 1990-10-16   Milwaukee Bucks    10-16

# Interlude: Combinatorics

In this project, we use **combinatorics** to answer the question: _how many players share a birthday in a given team?_  

Combinatorics is a branch of mathematics that deals with **counting and arrangements**. Specifically, we are interested in **combinations**, which allow us to generate **all unique pairs** of items without caring about the order.

---

## Concept

Suppose you have `n` people and you want to check all **pairs** to see if they share the same birthday.  

- **Combinations formula:**  

\[
C(n, 2) = {n!}/{2!(n-2)!}
\]

- This generates all unique pairs `(Person A, Person B)` where order does not matter.
- Perfect for the **Birthday Paradox problem**, where we compare birthdays among all pairs.

---

## Example

Suppose we have three people:

| Name  | Birthday   |
|-------|------------|
| John  | March 5th  |
| Mary  | Sept 20th  |
| Rob   | March 5th  |

We want to find all pairs and see which share birthdays.

### Step 1: Generate all pairs of names

```python
from itertools import combinations

names = ["John", "Mary", "Rob"]
list(combinations(names, 2))
```

#### Output
```
[('John', 'Mary'), ('John', 'Rob'), ('Mary', 'Rob')]
```

### Step 2: Generate all pairs of birthdays

```python
birthdays = ["March 5th", "Sept 20th", "March 5th"]
list(combinations(birthdays, 2))
```

#### Output
```
[('March 5th', 'Sept 20th'), ('March 5th', 'March 5th'), ('Sept 20th', 'March 5th')]
```
✅ The second pair matches, meaning John and Rob share a birthday.

### Step 3: Put it in a DataFrame

```python
import pandas as pd

names_df = pd.DataFrame(combinations(names, 2), columns=["Person 1", "Person 2"])
birthdays_df = pd.DataFrame(combinations(birthdays, 2), columns=["Birthday 1", "Birthday 2"])

df_concat = pd.concat([names_df, birthdays_df], axis=1)
df_concat
```

#### Resulting DataFrame:
| Person 1 | Person 2 | Birthday 1 | Birthday 2 |
| :--------: | :--------: | :----------: | :----------: |
| John     | Mary     | March 5th  | Sept 20th  |
| John     | Rob      | March 5th  | March 5th  |
| Mary     | Rob      | Sept 20th  | March 5th  |

### Step 4: Check for shared birthdays

```python
df_concat['Birthday 1'] == df_concat['Birthday 2']
```

#### Output

```
0    False
1     True
2    False
```

✅ Only John and Rob share the same birthday.

In [258]:
from itertools import combinations

In [259]:
names = ['John', 'Mary', 'Bob']
birthdays = ['March 5th', 'September 20th', 'March 5th']

In [260]:
# Note: we need to wrap it in a list to force display
list(combinations(names, 2))

[('John', 'Mary'), ('John', 'Bob'), ('Mary', 'Bob')]

In [261]:
# Note: we need to wrap it in a list to force display
list(combinations(birthdays, 2))

[('March 5th', 'September 20th'),
 ('March 5th', 'March 5th'),
 ('September 20th', 'March 5th')]

We can see how `March 5th` (John and Rob) are the same dates. Using Pandas:

In [262]:
names_df = pd.DataFrame(combinations(names, 2), columns=["Person 1", "Person 2"])
names_df

  Person 1 Person 2
0     John     Mary
1     John      Bob
2     Mary      Bob

In [263]:
birthdays_df = pd.DataFrame(combinations(birthdays, 2), columns=["Birthday 1", "Birthday 2"])
birthdays_df

       Birthday 1      Birthday 2
0       March 5th  September 20th
1       March 5th       March 5th
2  September 20th       March 5th

In [264]:
df_concat = pd.concat([names_df, birthdays_df], axis=1)
df_concat

  Person 1 Person 2      Birthday 1      Birthday 2
0     John     Mary       March 5th  September 20th
1     John      Bob       March 5th       March 5th
2     Mary      Bob  September 20th       March 5th

In [265]:
df_concat['Birthday 1'] == df_concat['Birthday 2']

0    False
1     True
2    False
dtype: bool

#### 5. How many pairs of players share a birthday for the Atlanta Hawks?

This first activity will probably be the tougher one, as you have to find a way to answer how many players share a birthday for a given team. This first activity is related to the Atlanta Hawks. Hopefully, once you solve this one, you'll be able to answer the rest of the activities pretty easily.

>
> **Note:** We're asking for "pairs" of players, not the total number of players that share birthdays.  
> Imagine there are four players: A, B, C, and D.  
> - A and B have the same birthday → 1 pair  
> - C and D have the same birthday → 1 pair  
> So, there are **two pairs of players** with the same birthday: the first pair is A and B, and the second pair is C and D.
>

In [266]:
atlanta_df = df.loc[df['Team'] == 'Atlanta Hawks']
atlanta_df.head()

               Player  Age Pos Birth Date           Team Birthday
24          Omer Asik   31   C 1997-05-13  Atlanta Hawks    05-13
55        Tarik Black   26   C 1998-11-30  Atlanta Hawks    11-30
78    Malcolm Brogdon   25  PG 1985-10-08  Atlanta Hawks    10-08
107       Alex Caruso   23  PG 1990-10-16  Atlanta Hawks    10-16
134  DeMarcus Cousins   27   C 1990-06-04  Atlanta Hawks    06-04

In [267]:
atlanta_df.shape

(22, 6)

In [268]:
name_df = pd.DataFrame(combinations(atlanta_df['Player'], 2), columns=['Player 1', 'Player 2'])
name_df

             Player 1          Player 2
0           Omer Asik       Tarik Black
1           Omer Asik   Malcolm Brogdon
2           Omer Asik       Alex Caruso
3           Omer Asik  DeMarcus Cousins
4           Omer Asik       Joel Embiid
..                ...               ...
226    Marquis Teague  Hassan Whiteside
227    Marquis Teague    Thaddeus Young
228         Ekpe Udoh  Hassan Whiteside
229         Ekpe Udoh    Thaddeus Young
230  Hassan Whiteside    Thaddeus Young

[231 rows x 2 columns]

In [269]:
birthday_df = pd.DataFrame(combinations(atlanta_df['Birthday'], 2), columns=['Birthday 1', 'Birthday 2'])
birthday_df

    Birthday 1 Birthday 2
0        05-13      11-30
1        05-13      10-08
2        05-13      10-16
3        05-13      06-04
4        05-13      04-14
..         ...        ...
226      10-17      05-11
227      10-17      09-24
228      05-15      05-11
229      05-15      09-24
230      05-11      09-24

[231 rows x 2 columns]

In [270]:
check_df = pd.concat([name_df, birthday_df], axis=1)
check_df

             Player 1          Player 2 Birthday 1 Birthday 2
0           Omer Asik       Tarik Black      05-13      11-30
1           Omer Asik   Malcolm Brogdon      05-13      10-08
2           Omer Asik       Alex Caruso      05-13      10-16
3           Omer Asik  DeMarcus Cousins      05-13      06-04
4           Omer Asik       Joel Embiid      05-13      04-14
..                ...               ...        ...        ...
226    Marquis Teague  Hassan Whiteside      10-17      05-11
227    Marquis Teague    Thaddeus Young      10-17      09-24
228         Ekpe Udoh  Hassan Whiteside      05-15      05-11
229         Ekpe Udoh    Thaddeus Young      05-15      09-24
230  Hassan Whiteside    Thaddeus Young      05-11      09-24

[231 rows x 4 columns]

In [ ]:
check_df['Birthday 1'] == check_df['Birthday 2']().sum()

np.int64(0)

In [272]:
check_df['Birthday 1'] == check_df['Birthday 2']

0      False
1      False
2      False
3      False
4      False
       ...
226    False
227    False
228    False
229    False
230    False
Length: 231, dtype: bool

In [273]:
check_df.loc[(check_df['Birthday 1'] == check_df['Birthday 2'])]

Empty DataFrame
Columns: [Player 1, Player 2, Birthday 1, Birthday 2]
Index: []

#### 6. How many pairs of players share a birthday in the Cleveland Cavaliers?

In [275]:
cleveland_df = df.loc[df['Team'] == 'Cleveland Cavaliers']
cleveland_df

                  Player  Age    Pos Birth Date                 Team Birthday
17            OG Anunoby   20     SF 1985-11-03  Cleveland Cavaliers    11-03
51            Khem Birch   25      C 1995-07-17  Cleveland Cavaliers    07-17
75          Corey Brewer   31  SF-SG 1992-12-20  Cleveland Cavaliers    12-20
115            Ian Clark   26     SG 2000-01-16  Cleveland Cavaliers    01-16
133        Matt Costello   24      C 1996-09-23  Cleveland Cavaliers    09-23
166           Larry Drew   27     PG 1994-11-10  Cleveland Cavaliers    11-10
195  Dorian Finney-Smith   24     PF 1999-08-03  Cleveland Cavaliers    08-03
230      Daniel Hamilton   22     SG 1989-06-11  Cleveland Cavaliers    06-11
266          George Hill   31     PG 1987-10-27  Cleveland Cavaliers    10-27
286       Ersan Ilyasova   30     PF 1988-08-18  Cleveland Cavaliers    08-18
313        Brice Johnson   23     PF 1998-09-27  Cleveland Cavaliers    09-27
360       Walt Lemon Jr.   25     PG 1987-01-12  Cleveland Cavaliers    01-12
391      Wesley Matthews   31     SF 1993-11-12  Cleveland Cavaliers    11-12
416         Paul Millsap   32     PF 1985-11-07  Cleveland Cavaliers    11-07
450          Larry Nance   25      C 1986-06-19  Cleveland Cavaliers    06-19
467         Semi Ojeleye   23     PF 1999-07-28  Cleveland Cavaliers    07-28
498     London Perrantes   23     PG 1994-07-21  Cleveland Cavaliers    07-21
525   Malachi Richardson   22     SG 1989-03-28  Cleveland Cavaliers    03-28
557         Kyle Singler   29     SF 1990-11-13  Cleveland Cavaliers    11-13
612         Kemba Walker   27     PG 1995-02-16  Cleveland Cavaliers    02-16
640        Troy Williams   23     SF 1990-06-23  Cleveland Cavaliers    06-23

In [276]:
player_df = pd.DataFrame(combinations(cleveland_df['Player'], 2), columns=['Player 1', 'Player 2'])
player_df

               Player 1       Player 2
0            OG Anunoby     Khem Birch
1            OG Anunoby   Corey Brewer
2            OG Anunoby      Ian Clark
3            OG Anunoby  Matt Costello
4            OG Anunoby     Larry Drew
..                  ...            ...
205  Malachi Richardson   Kemba Walker
206  Malachi Richardson  Troy Williams
207        Kyle Singler   Kemba Walker
208        Kyle Singler  Troy Williams
209        Kemba Walker  Troy Williams

[210 rows x 2 columns]

In [277]:
birth_df = pd.DataFrame(combinations(cleveland_df['Birthday'], 2), columns=['Birthday 1', 'Birthday 2'])
birth_df

    Birthday 1 Birthday 2
0        11-03      07-17
1        11-03      12-20
2        11-03      01-16
3        11-03      09-23
4        11-03      11-10
..         ...        ...
205      03-28      02-16
206      03-28      06-23
207      11-13      02-16
208      11-13      06-23
209      02-16      06-23

[210 rows x 2 columns]

In [279]:
cleveland_birth_df = pd.concat([player_df, birth_df], axis=1)
cleveland_birth_df

               Player 1       Player 2 Birthday 1 Birthday 2
0            OG Anunoby     Khem Birch      11-03      07-17
1            OG Anunoby   Corey Brewer      11-03      12-20
2            OG Anunoby      Ian Clark      11-03      01-16
3            OG Anunoby  Matt Costello      11-03      09-23
4            OG Anunoby     Larry Drew      11-03      11-10
..                  ...            ...        ...        ...
205  Malachi Richardson   Kemba Walker      03-28      02-16
206  Malachi Richardson  Troy Williams      03-28      06-23
207        Kyle Singler   Kemba Walker      11-13      02-16
208        Kyle Singler  Troy Williams      11-13      06-23
209        Kemba Walker  Troy Williams      02-16      06-23

[210 rows x 4 columns]

In [281]:
(cleveland_birth_df['Birthday 1'] == cleveland_birth_df['Birthday 2']).sum()

np.int64(0)

In [283]:
cleveland_birth_df.loc[cleveland_birth_df['Birthday 1'] == cleveland_birth_df['Birthday 2']]

Empty DataFrame
Columns: [Player 1, Player 2, Birthday 1, Birthday 2]
Index: []