In [84]:
import pandas as pd
import numpy as np

# Importing modueles

In [85]:
# Reading data
df = pd.read_csv("data/sales1_data.csv")

In [86]:
# Retriving top 5 rows
df.head()

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [87]:
# Retriving number of rows & columns
df.shape

(25, 4)

In [88]:
# Name of columns
df.columns

Index(['Date', 'Product', 'Sales', 'Region'], dtype='object')

In [89]:
# Data type of columns
df.dtypes

Date        object
Product     object
Sales      float64
Region      object
dtype: object

In [90]:
df['Date'].unique()

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25'], dtype=object)

In [92]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df.head()
# Converts the Date column from string → datetime format.

        Date   Product  Sales Region
0 2023-01-01  Product3  738.0   West
1 2023-01-02  Product2  868.0  North
2 2023-01-03  Product2  554.0   West
3 2023-01-04  Product1  618.0  South
4 2023-01-05  Product3  501.0   East

In [93]:
df.dtypes

Date       datetime64[ns]
Product            object
Sales             float64
Region             object
dtype: object

In [94]:
df.describe()
# Summary of table

                      Date       Sales
count                   25   19.000000
mean   2023-01-13 00:00:00  554.000000
min    2023-01-01 00:00:00  124.000000
25%    2023-01-07 00:00:00  381.500000
50%    2023-01-13 00:00:00  554.000000
75%    2023-01-19 00:00:00  737.500000
max    2023-01-25 00:00:00  868.000000
std                    NaN  231.543372

In [95]:
# Checking if null value is present or not
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [96]:
df

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East
5  2023-01-06  Product1    NaN   West
6  2023-01-07  Product3  339.0  South
7  2023-01-08  Product3  280.0  South
8  2023-01-09  Product2  806.0  North
9  2023-01-10  Product2  816.0  South
10 2023-01-11  Product3  469.0   West
11 2023-01-12  Product3    NaN   East
12 2023-01-13  Product3    NaN   East
13 2023-01-14  Product3  676.0   East
14 2023-01-15  Product1  183.0  South
15 2023-01-16  Product1  424.0  South
16 2023-01-17  Product1    NaN  South
17 2023-01-18  Product1    NaN  South
18 2023-01-19  Product2  124.0  North
19 2023-01-20  Product3  732.0   West
20 2023-01-21  Product2    NaN   West
21 2023-01-22  Product3  296.0   West
22 2023-01-23  Product2  737.0   West
23 2023-01-24  Product3  531.0   East
24 2023-01-25  Product2  834.0  North

In [97]:
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())
df
# filling null values

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East
5  2023-01-06  Product1  554.0   West
6  2023-01-07  Product3  339.0  South
7  2023-01-08  Product3  280.0  South
8  2023-01-09  Product2  806.0  North
9  2023-01-10  Product2  816.0  South
10 2023-01-11  Product3  469.0   West
11 2023-01-12  Product3  554.0   East
12 2023-01-13  Product3  554.0   East
13 2023-01-14  Product3  676.0   East
14 2023-01-15  Product1  183.0  South
15 2023-01-16  Product1  424.0  South
16 2023-01-17  Product1  554.0  South
17 2023-01-18  Product1  554.0  South
18 2023-01-19  Product2  124.0  North
19 2023-01-20  Product3  732.0   West
20 2023-01-21  Product2  554.0   West
21 2023-01-22  Product3  296.0   West
22 2023-01-23  Product2  737.0   West
23 2023-01-24  Product3  531.0   East
24 2023-01-25  Product2  834.0  North

In [ ]:
df = df.dropna()
df
# dropping nul columns

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East
6  2023-01-07  Product3  339.0  South
7  2023-01-08  Product3  280.0  South
8  2023-01-09  Product2  806.0  North
9  2023-01-10  Product2  816.0  South
10 2023-01-11  Product3  469.0   West
13 2023-01-14  Product3  676.0   East
14 2023-01-15  Product1  183.0  South
15 2023-01-16  Product1  424.0  South
18 2023-01-19  Product2  124.0  North
19 2023-01-20  Product3  732.0   West
21 2023-01-22  Product3  296.0   West
22 2023-01-23  Product2  737.0   West
23 2023-01-24  Product3  531.0   East
24 2023-01-25  Product2  834.0  North

In [98]:
df = df.drop_duplicates()
# dropping duplicate values

In [99]:
df = df.sort_values(by='Date')
df
# sorting date column

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East
5  2023-01-06  Product1  554.0   West
6  2023-01-07  Product3  339.0  South
7  2023-01-08  Product3  280.0  South
8  2023-01-09  Product2  806.0  North
9  2023-01-10  Product2  816.0  South
10 2023-01-11  Product3  469.0   West
11 2023-01-12  Product3  554.0   East
12 2023-01-13  Product3  554.0   East
13 2023-01-14  Product3  676.0   East
14 2023-01-15  Product1  183.0  South
15 2023-01-16  Product1  424.0  South
16 2023-01-17  Product1  554.0  South
17 2023-01-18  Product1  554.0  South
18 2023-01-19  Product2  124.0  North
19 2023-01-20  Product3  732.0   West
20 2023-01-21  Product2  554.0   West
21 2023-01-22  Product3  296.0   West
22 2023-01-23  Product2  737.0   West
23 2023-01-24  Product3  531.0   East
24 2023-01-25  Product2  834.0  North

In [100]:
# Create new feature
df['Year'] = df['Date'].dt.year
df

         Date   Product  Sales Region  Year
0  2023-01-01  Product3  738.0   West  2023
1  2023-01-02  Product2  868.0  North  2023
2  2023-01-03  Product2  554.0   West  2023
3  2023-01-04  Product1  618.0  South  2023
4  2023-01-05  Product3  501.0   East  2023
5  2023-01-06  Product1  554.0   West  2023
6  2023-01-07  Product3  339.0  South  2023
7  2023-01-08  Product3  280.0  South  2023
8  2023-01-09  Product2  806.0  North  2023
9  2023-01-10  Product2  816.0  South  2023
10 2023-01-11  Product3  469.0   West  2023
11 2023-01-12  Product3  554.0   East  2023
12 2023-01-13  Product3  554.0   East  2023
13 2023-01-14  Product3  676.0   East  2023
14 2023-01-15  Product1  183.0  South  2023
15 2023-01-16  Product1  424.0  South  2023
16 2023-01-17  Product1  554.0  South  2023
17 2023-01-18  Product1  554.0  South  2023
18 2023-01-19  Product2  124.0  North  2023
19 2023-01-20  Product3  732.0   West  2023
20 2023-01-21  Product2  554.0   West  2023
21 2023-01-22  Product3  296.0   West  2023
22 2023-01-23  Product2  737.0   West  2023
23 2023-01-24  Product3  531.0   East  2023
24 2023-01-25  Product2  834.0  North  2023

In [102]:
df['Month'] = df['Date'].dt.month
df

         Date   Product  Sales Region  Year  Month
0  2023-01-01  Product3  738.0   West  2023      1
1  2023-01-02  Product2  868.0  North  2023      1
2  2023-01-03  Product2  554.0   West  2023      1
3  2023-01-04  Product1  618.0  South  2023      1
4  2023-01-05  Product3  501.0   East  2023      1
5  2023-01-06  Product1  554.0   West  2023      1
6  2023-01-07  Product3  339.0  South  2023      1
7  2023-01-08  Product3  280.0  South  2023      1
8  2023-01-09  Product2  806.0  North  2023      1
9  2023-01-10  Product2  816.0  South  2023      1
10 2023-01-11  Product3  469.0   West  2023      1
11 2023-01-12  Product3  554.0   East  2023      1
12 2023-01-13  Product3  554.0   East  2023      1
13 2023-01-14  Product3  676.0   East  2023      1
14 2023-01-15  Product1  183.0  South  2023      1
15 2023-01-16  Product1  424.0  South  2023      1
16 2023-01-17  Product1  554.0  South  2023      1
17 2023-01-18  Product1  554.0  South  2023      1
18 2023-01-19  Product2  124.0  North  2023      1
19 2023-01-20  Product3  732.0   West  2023      1
20 2023-01-21  Product2  554.0   West  2023      1
21 2023-01-22  Product3  296.0   West  2023      1
22 2023-01-23  Product2  737.0   West  2023      1
23 2023-01-24  Product3  531.0   East  2023      1
24 2023-01-25  Product2  834.0  North  2023      1

In [104]:
df['Day'] = df['Date'].dt.date
df

         Date   Product  Sales Region  Year  Month         Day
0  2023-01-01  Product3  738.0   West  2023      1  2023-01-01
1  2023-01-02  Product2  868.0  North  2023      1  2023-01-02
2  2023-01-03  Product2  554.0   West  2023      1  2023-01-03
3  2023-01-04  Product1  618.0  South  2023      1  2023-01-04
4  2023-01-05  Product3  501.0   East  2023      1  2023-01-05
5  2023-01-06  Product1  554.0   West  2023      1  2023-01-06
6  2023-01-07  Product3  339.0  South  2023      1  2023-01-07
7  2023-01-08  Product3  280.0  South  2023      1  2023-01-08
8  2023-01-09  Product2  806.0  North  2023      1  2023-01-09
9  2023-01-10  Product2  816.0  South  2023      1  2023-01-10
10 2023-01-11  Product3  469.0   West  2023      1  2023-01-11
11 2023-01-12  Product3  554.0   East  2023      1  2023-01-12
12 2023-01-13  Product3  554.0   East  2023      1  2023-01-13
13 2023-01-14  Product3  676.0   East  2023      1  2023-01-14
14 2023-01-15  Product1  183.0  South  2023      1  2023-01-15
15 2023-01-16  Product1  424.0  South  2023      1  2023-01-16
16 2023-01-17  Product1  554.0  South  2023      1  2023-01-17
17 2023-01-18  Product1  554.0  South  2023      1  2023-01-18
18 2023-01-19  Product2  124.0  North  2023      1  2023-01-19
19 2023-01-20  Product3  732.0   West  2023      1  2023-01-20
20 2023-01-21  Product2  554.0   West  2023      1  2023-01-21
21 2023-01-22  Product3  296.0   West  2023      1  2023-01-22
22 2023-01-23  Product2  737.0   West  2023      1  2023-01-23
23 2023-01-24  Product3  531.0   East  2023      1  2023-01-24
24 2023-01-25  Product2  834.0  North  2023      1  2023-01-25