In [145]:
import numpy as np
import pandas as pd

In [146]:
df = pd.read_csv('Airbnb_Open_Data.csv', index_col='id')

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_9750/4290526060.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Airbnb_Open_Data.csv', index_col='id')

In [147]:
df.head()

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
id,,,,,,,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [148]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [149]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
id,,,,,,,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102599 entries, 1001254 to 6094647
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   NAME                            102349 non-null  object
 1   host id                         102599 non-null  int64
 2   host_identity_verified          102310 non-null  object
 3   host name                       102193 non-null  object
 4   neighbourhood group             102570 non-null  object
 5   neighbourhood                   102583 non-null  object
 6   lat                             102591 non-null  float64
 7   long                            102591 non-null  float64
 8   country                         102067 non-null  object
 9   country code                    102468 non-null  object
 10  instant_bookable                102494 non-null  object
 11  cancellation_policy             102523 non-null  object
 12  room type                       102599 non-null  object
 13  Construction year               102385 non-null  float64
 14  price                           102352 non-null  object
 15  service fee                     102326 non-null  object
 16  minimum nights                  102190 non-null  float64
 17  number of reviews               102416 non-null  float64
 18  last review                     86706 non-null   object
 19  reviews per month               86720 non-null   float64
 20  review rate number              102273 non-null  float64
 21  calculated host listings count  102280 non-null  float64
 22  availability 365                102151 non-null  float64
 23  house_rules                     50468 non-null   object
 24  license                         2 non-null       object
dtypes: float64(9), int64(1), object(15)
memory usage: 20.4+ MB

In [151]:
df.tail()

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
id,,,,,,,,,,,,,,,,,,,,,,,,,
6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [152]:
pd.set_option('display.max_columns', 25)

In [153]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
id,,,,,,,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [154]:
name = df['NAME']
name

id
1001254                  Clean & quiet apt home by the park
1002102                               Skylit Midtown Castle
1002403                 THE VILLAGE OF HARLEM....NEW YORK !
1002755                                                 NaN
1003689    Entire Apt: Spacious Studio/Loft by central park
                                 ...
6092437                          Spare room in Williamsburg
6092990                       Best Location near Columbia U
6093542                      Comfy, bright room in Brooklyn
6094094                    Big Studio-One Stop from Midtown
6094647                                585 sf Luxury Studio
Name: NAME, Length: 102599, dtype: object

In [155]:
subset = df[['NAME', 'country']]
subset

                                                     NAME        country
id
1001254                Clean & quiet apt home by the park  United States
1002102                             Skylit Midtown Castle  United States
1002403               THE VILLAGE OF HARLEM....NEW YORK !  United States
1002755                                               NaN  United States
1003689  Entire Apt: Spacious Studio/Loft by central park  United States
...                                                   ...            ...
6092437                        Spare room in Williamsburg  United States
6092990                     Best Location near Columbia U  United States
6093542                    Comfy, bright room in Brooklyn  United States
6094094                  Big Studio-One Stop from Midtown  United States
6094647                              585 sf Luxury Studio  United States

[102599 rows x 2 columns]

In [156]:
df.iloc[0:5]

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
id,,,,,,,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [157]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [158]:
Countries = ['United States', 'India', 'United Kingdom', 'Germany']
filt = df['country'].isin(Countries)
df.loc[filt, 'country']

id
1001254    United States
1002102    United States
1002403    United States
1002755    United States
1003689    United States
               ...
6092437    United States
6092990    United States
6093542    United States
6094094    United States
6094647    United States
Name: country, Length: 102067, dtype: object

In [159]:
df.sort_values(by=['country'], ascending = [True], inplace=True)
df['country'].head(20)

id
1001254     United States
38763192    United States
38762639    United States
38762087    United States
38761535    United States
38760982    United States
38760430    United States
38759878    United States
38759326    United States
38758773    United States
38763744    United States
38758221    United States
38757116    United States
38756564    United States
38756012    United States
38755459    United States
38754907    United States
38754355    United States
38753803    United States
38753250    United States
Name: country, dtype: object

In [160]:
df.columns

Index(['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [161]:
columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']

columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

In [162]:
len(columns_to_keep)

19

In [163]:
len(columns_to_drop)

6

## 1st method -> Data filtering

In [164]:
data = df[columns_to_keep]

In [165]:
data.shape

(102599, 19)

In [166]:
data

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
id,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
38763192,Big One Bedroom Directly Across from Central P...,36257056231,unconfirmed,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,False,strict,Entire home/apt,2013.0,$286,$57,2.0,1.0,9/10/2017
38762639,Affordable 2 Bedroom on the UES!!!,83771419475,unconfirmed,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,True,moderate,Entire home/apt,2010.0,$858,$172,3.0,3.0,9/28/2017
38762087,Charming 1 br apartment,8856169091,verified,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,True,strict,Entire home/apt,2013.0,$766,$153,2.0,13.0,4/15/2018
38761535,Masterbed w/private bath nr G train in BedStuy,51789425655,unconfirmed,Vandra,Brooklyn,Bedford-Stuyvesant,40.68797,-73.95920,United States,US,True,moderate,Private room,2021.0,$198,$40,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56986882,Charming Park Slope Apt (fits up to 6 ppl)!,2778317625,unconfirmed,Julia,Brooklyn,Windsor Terrace,40.66063,-73.98348,NaN,US,False,moderate,Entire home/apt,2004.0,$765,$153,3.0,0.0,NaN
56987435,Studio with amazing view,25057683830,unconfirmed,Carolann,Manhattan,Financial District,40.70588,-74.01590,NaN,US,True,strict,Entire home/apt,2010.0,$201,$40,300.0,0.0,NaN
56987987,Private apartment in new Brooklyn building!,35509233859,unconfirmed,Steven & Melissa,Brooklyn,Bedford-Stuyvesant,40.68438,-73.95299,NaN,US,False,strict,Entire home/apt,2019.0,$132,$26,2.0,33.0,5/22/2019
56988539,UES(mini loft)Clean flex room (Female Only),76384585618,verified,Eun M,Manhattan,Upper East Side,40.77759,-73.95321,NaN,US,False,strict,Private room,2022.0,$940,$188,1.0,133.0,6/19/2019
56989092,Luxury Loft in Williamsburg,5156600288,verified,Aaron,Brooklyn,Williamsburg,40.71218,-73.96048,NaN,US,False,strict,Entire home/apt,2020.0,"$1,020",$204,3.0,8.0,8/26/2018

## 2nd method -> Dropping columns

In [167]:
df.drop(columns = columns_to_drop, inplace=True)

In [168]:
df.shape

(102599, 19)

## Renaming column

In [169]:
df.rename(columns = {"NAME" : "Name"}, inplace = True)

In [170]:
data.rename(columns = {"NAME": "Name"}, inplace = True)

In [171]:
data

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
id,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
38763192,Big One Bedroom Directly Across from Central P...,36257056231,unconfirmed,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,False,strict,Entire home/apt,2013.0,$286,$57,2.0,1.0,9/10/2017
38762639,Affordable 2 Bedroom on the UES!!!,83771419475,unconfirmed,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,True,moderate,Entire home/apt,2010.0,$858,$172,3.0,3.0,9/28/2017
38762087,Charming 1 br apartment,8856169091,verified,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,True,strict,Entire home/apt,2013.0,$766,$153,2.0,13.0,4/15/2018
38761535,Masterbed w/private bath nr G train in BedStuy,51789425655,unconfirmed,Vandra,Brooklyn,Bedford-Stuyvesant,40.68797,-73.95920,United States,US,True,moderate,Private room,2021.0,$198,$40,1.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56986882,Charming Park Slope Apt (fits up to 6 ppl)!,2778317625,unconfirmed,Julia,Brooklyn,Windsor Terrace,40.66063,-73.98348,NaN,US,False,moderate,Entire home/apt,2004.0,$765,$153,3.0,0.0,NaN
56987435,Studio with amazing view,25057683830,unconfirmed,Carolann,Manhattan,Financial District,40.70588,-74.01590,NaN,US,True,strict,Entire home/apt,2010.0,$201,$40,300.0,0.0,NaN
56987987,Private apartment in new Brooklyn building!,35509233859,unconfirmed,Steven & Melissa,Brooklyn,Bedford-Stuyvesant,40.68438,-73.95299,NaN,US,False,strict,Entire home/apt,2019.0,$132,$26,2.0,33.0,5/22/2019
56988539,UES(mini loft)Clean flex room (Female Only),76384585618,verified,Eun M,Manhattan,Upper East Side,40.77759,-73.95321,NaN,US,False,strict,Private room,2022.0,$940,$188,1.0,133.0,6/19/2019
56989092,Luxury Loft in Williamsburg,5156600288,verified,Aaron,Brooklyn,Williamsburg,40.71218,-73.96048,NaN,US,False,strict,Entire home/apt,2020.0,"$1,020",$204,3.0,8.0,8/26/2018

In [172]:
data.shape

(102599, 19)

In [173]:
data.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [174]:
new_column_names = []
for i in data:
  new_column_names.append(i.upper())
new_column_names

['NAME',
 'HOST ID',
 'HOST_IDENTITY_VERIFIED',
 'HOST NAME',
 'NEIGHBOURHOOD GROUP',
 'NEIGHBOURHOOD',
 'LAT',
 'LONG',
 'COUNTRY',
 'COUNTRY CODE',
 'INSTANT_BOOKABLE',
 'CANCELLATION_POLICY',
 'ROOM TYPE',
 'CONSTRUCTION YEAR',
 'PRICE',
 'SERVICE FEE',
 'MINIMUM NIGHTS',
 'NUMBER OF REVIEWS',
 'LAST REVIEW']

In [175]:
new_dataframe_to_modify = data.copy()

In [176]:
new_dataframe_to_modify.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [177]:
new_dataframe_to_modify.columns = new_column_names

In [178]:
new_dataframe_to_modify.columns

Index(['NAME', 'HOST ID', 'HOST_IDENTITY_VERIFIED', 'HOST NAME',
       'NEIGHBOURHOOD GROUP', 'NEIGHBOURHOOD', 'LAT', 'LONG', 'COUNTRY',
       'COUNTRY CODE', 'INSTANT_BOOKABLE', 'CANCELLATION_POLICY', 'ROOM TYPE',
       'CONSTRUCTION YEAR', 'PRICE', 'SERVICE FEE', 'MINIMUM NIGHTS',
       'NUMBER OF REVIEWS', 'LAST REVIEW'],
      dtype='object')

In [179]:
df.duplicated().sum()

np.int64(541)

In [180]:
df.drop_duplicates(inplace=True)

In [181]:
df.duplicated().sum()

np.int64(0)

In [182]:
df.isna().sum()

Name                        250
host id                       0
host_identity_verified      289
host name                   404
neighbourhood group          29
neighbourhood                16
lat                           8
long                          8
country                     532
country code                131
instant_bookable            105
cancellation_policy          76
room type                     0
Construction year           214
price                       247
service fee                 273
minimum nights              400
number of reviews           183
last review               15832
dtype: int64

In [183]:
df.dropna(inplace = True)

In [184]:
df.isna().sum()

Name                      0
host id                   0
host_identity_verified    0
host name                 0
neighbourhood group       0
neighbourhood             0
lat                       0
long                      0
country                   0
country code              0
instant_bookable          0
cancellation_policy       0
room type                 0
Construction year         0
price                     0
service fee               0
minimum nights            0
number of reviews         0
last review               0
dtype: int64

In [185]:
df.columns

Index(['Name', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review'],
      dtype='object')

In [186]:
df['host_identity_verified']

id
1001254     unconfirmed
38763192    unconfirmed
38762639    unconfirmed
38762087       verified
38760982       verified
               ...
19839184       verified
19838632    unconfirmed
19837528    unconfirmed
19836423       verified
19835318    unconfirmed
Name: host_identity_verified, Length: 83969, dtype: object

In [187]:
df['host_identity_verified'] = df['host_identity_verified'].str.upper()

In [188]:
df

,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
id,,,,,,,,,,,,,,,,,,,
1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021
38763192,Big One Bedroom Directly Across from Central P...,36257056231,UNCONFIRMED,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,False,strict,Entire home/apt,2013.0,$286,$57,2.0,1.0,9/10/2017
38762639,Affordable 2 Bedroom on the UES!!!,83771419475,UNCONFIRMED,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,True,moderate,Entire home/apt,2010.0,$858,$172,3.0,3.0,9/28/2017
38762087,Charming 1 br apartment,8856169091,VERIFIED,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,True,strict,Entire home/apt,2013.0,$766,$153,2.0,13.0,4/15/2018
38760982,Artist's Room in Prime Bushwick,12458494587,VERIFIED,Lux,Brooklyn,Bushwick,40.70100,-73.91986,United States,US,False,moderate,Private room,2016.0,$92,$18,1.0,77.0,7/7/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19839184,Modern Living in Soho/Noho/West Village,62024966266,VERIFIED,Jeff,Manhattan,Greenwich Village,40.72674,-73.99673,United States,US,True,moderate,Entire home/apt,2021.0,$451,$90,3.0,6.0,7/1/2019
19838632,Central Park Spacious Room,74378693322,UNCONFIRMED,Hongzhi,Manhattan,Upper West Side,40.79908,-73.96215,United States,US,True,moderate,Private room,2017.0,$763,$153,1.0,14.0,8/23/2018
19837528,Prime East Village Manhattan w/ Beautiful Back...,58958151239,UNCONFIRMED,Thomas,Manhattan,East Village,40.72769,-73.98498,United States,US,True,moderate,Private room,2011.0,"$1,121",$224,1.0,3.0,6/22/2019
19836423,Brooklyn home away from home,36982711686,VERIFIED,Sofiya,Brooklyn,Sunset Park,40.66153,-73.99297,United States,US,False,strict,Private room,2018.0,$399,$80,1.0,6.0,6/23/2019
19835318,Stunning bedroom in trendy Williamsburg!,77736603165,UNCONFIRMED,Nina,Brooklyn,Williamsburg,40.71407,-73.93936,United States,US,True,strict,Private room,2014.0,$186,$37,30.0,2.0,7/6/2019

In [189]:
df['instant_bookable']

id
1001254     False
38763192    False
38762639     True
38762087     True
38760982    False
            ...
19839184     True
19838632     True
19837528     True
19836423    False
19835318     True
Name: instant_bookable, Length: 83969, dtype: object

In [190]:
df['instant_bookable'] = df['instant_bookable'].apply(lambda x : 1 if x == True else 0)

In [191]:
df.reset_index(inplace=True)

In [192]:
type(df['instant_bookable'][15])

numpy.int64

In [193]:
data['price']

id
1001254       $966
38763192      $286
38762639      $858
38762087      $766
38761535      $198
             ...
56986882      $765
56987435      $201
56987987      $132
56988539      $940
56989092    $1,020
Name: price, Length: 102599, dtype: object

In [194]:
df['price'] = df['price'].str.replace("$", "")

In [195]:
df['price']

0          966
1          286
2          858
3          766
4           92
          ...
83964      451
83965      763
83966    1,121
83967      399
83968      186
Name: price, Length: 83969, dtype: object

In [196]:
df['price'] = df['price'].str.replace(',', '')

In [197]:
df['price']

0         966
1         286
2         858
3         766
4          92
         ...
83964     451
83965     763
83966    1121
83967     399
83968     186
Name: price, Length: 83969, dtype: object

In [198]:
df['price'][15]

'761 '

In [199]:
df['price'] = df['price'].replace([' ', ''])

/var/folders/zs/6h03lndj5114078br2jdh8380000gn/T/ipykernel_9750/1521255269.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df['price'] = df['price'].replace([' ', ''])

In [200]:
type(df['price'][15])

str

In [201]:
df['price'] = df['price'].astype(int)

In [ ]:
type(df['price'][15])

numpy.int64

In [204]:
df

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0,10/19/2021
1,38763192,Big One Bedroom Directly Across from Central P...,36257056231,UNCONFIRMED,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,0,strict,Entire home/apt,2013.0,286,$57,2.0,1.0,9/10/2017
2,38762639,Affordable 2 Bedroom on the UES!!!,83771419475,UNCONFIRMED,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,1,moderate,Entire home/apt,2010.0,858,$172,3.0,3.0,9/28/2017
3,38762087,Charming 1 br apartment,8856169091,VERIFIED,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,1,strict,Entire home/apt,2013.0,766,$153,2.0,13.0,4/15/2018
4,38760982,Artist's Room in Prime Bushwick,12458494587,VERIFIED,Lux,Brooklyn,Bushwick,40.70100,-73.91986,United States,US,0,moderate,Private room,2016.0,92,$18,1.0,77.0,7/7/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,19839184,Modern Living in Soho/Noho/West Village,62024966266,VERIFIED,Jeff,Manhattan,Greenwich Village,40.72674,-73.99673,United States,US,1,moderate,Entire home/apt,2021.0,451,$90,3.0,6.0,7/1/2019
83965,19838632,Central Park Spacious Room,74378693322,UNCONFIRMED,Hongzhi,Manhattan,Upper West Side,40.79908,-73.96215,United States,US,1,moderate,Private room,2017.0,763,$153,1.0,14.0,8/23/2018
83966,19837528,Prime East Village Manhattan w/ Beautiful Back...,58958151239,UNCONFIRMED,Thomas,Manhattan,East Village,40.72769,-73.98498,United States,US,1,moderate,Private room,2011.0,1121,$224,1.0,3.0,6/22/2019
83967,19836423,Brooklyn home away from home,36982711686,VERIFIED,Sofiya,Brooklyn,Sunset Park,40.66153,-73.99297,United States,US,0,strict,Private room,2018.0,399,$80,1.0,6.0,6/23/2019
83968,19835318,Stunning bedroom in trendy Williamsburg!,77736603165,UNCONFIRMED,Nina,Brooklyn,Williamsburg,40.71407,-73.93936,United States,US,1,strict,Private room,2014.0,186,$37,30.0,2.0,7/6/2019

In [205]:
df.to_csv('cleaned_data.csv')

In [206]:
df_cleaned = pd.read_csv('cleaned_data.csv')
df_cleaned

,Unnamed: 0,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0,10/19/2021
1,1,38763192,Big One Bedroom Directly Across from Central P...,36257056231,UNCONFIRMED,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,0,strict,Entire home/apt,2013.0,286,$57,2.0,1.0,9/10/2017
2,2,38762639,Affordable 2 Bedroom on the UES!!!,83771419475,UNCONFIRMED,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,1,moderate,Entire home/apt,2010.0,858,$172,3.0,3.0,9/28/2017
3,3,38762087,Charming 1 br apartment,8856169091,VERIFIED,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,1,strict,Entire home/apt,2013.0,766,$153,2.0,13.0,4/15/2018
4,4,38760982,Artist's Room in Prime Bushwick,12458494587,VERIFIED,Lux,Brooklyn,Bushwick,40.70100,-73.91986,United States,US,0,moderate,Private room,2016.0,92,$18,1.0,77.0,7/7/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,83964,19839184,Modern Living in Soho/Noho/West Village,62024966266,VERIFIED,Jeff,Manhattan,Greenwich Village,40.72674,-73.99673,United States,US,1,moderate,Entire home/apt,2021.0,451,$90,3.0,6.0,7/1/2019
83965,83965,19838632,Central Park Spacious Room,74378693322,UNCONFIRMED,Hongzhi,Manhattan,Upper West Side,40.79908,-73.96215,United States,US,1,moderate,Private room,2017.0,763,$153,1.0,14.0,8/23/2018
83966,83966,19837528,Prime East Village Manhattan w/ Beautiful Back...,58958151239,UNCONFIRMED,Thomas,Manhattan,East Village,40.72769,-73.98498,United States,US,1,moderate,Private room,2011.0,1121,$224,1.0,3.0,6/22/2019
83967,83967,19836423,Brooklyn home away from home,36982711686,VERIFIED,Sofiya,Brooklyn,Sunset Park,40.66153,-73.99297,United States,US,0,strict,Private room,2018.0,399,$80,1.0,6.0,6/23/2019
83968,83968,19835318,Stunning bedroom in trendy Williamsburg!,77736603165,UNCONFIRMED,Nina,Brooklyn,Williamsburg,40.71407,-73.93936,United States,US,1,strict,Private room,2014.0,186,$37,30.0,2.0,7/6/2019

In [207]:
df.to_csv('cleaned_df.csv', index=False)

In [208]:
df_clean = pd.read_csv('cleaned_df.csv')
df_clean

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020.0,966,$193,10.0,9.0,10/19/2021
1,38763192,Big One Bedroom Directly Across from Central P...,36257056231,UNCONFIRMED,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,0,strict,Entire home/apt,2013.0,286,$57,2.0,1.0,9/10/2017
2,38762639,Affordable 2 Bedroom on the UES!!!,83771419475,UNCONFIRMED,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,1,moderate,Entire home/apt,2010.0,858,$172,3.0,3.0,9/28/2017
3,38762087,Charming 1 br apartment,8856169091,VERIFIED,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,1,strict,Entire home/apt,2013.0,766,$153,2.0,13.0,4/15/2018
4,38760982,Artist's Room in Prime Bushwick,12458494587,VERIFIED,Lux,Brooklyn,Bushwick,40.70100,-73.91986,United States,US,0,moderate,Private room,2016.0,92,$18,1.0,77.0,7/7/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,19839184,Modern Living in Soho/Noho/West Village,62024966266,VERIFIED,Jeff,Manhattan,Greenwich Village,40.72674,-73.99673,United States,US,1,moderate,Entire home/apt,2021.0,451,$90,3.0,6.0,7/1/2019
83965,19838632,Central Park Spacious Room,74378693322,UNCONFIRMED,Hongzhi,Manhattan,Upper West Side,40.79908,-73.96215,United States,US,1,moderate,Private room,2017.0,763,$153,1.0,14.0,8/23/2018
83966,19837528,Prime East Village Manhattan w/ Beautiful Back...,58958151239,UNCONFIRMED,Thomas,Manhattan,East Village,40.72769,-73.98498,United States,US,1,moderate,Private room,2011.0,1121,$224,1.0,3.0,6/22/2019
83967,19836423,Brooklyn home away from home,36982711686,VERIFIED,Sofiya,Brooklyn,Sunset Park,40.66153,-73.99297,United States,US,0,strict,Private room,2018.0,399,$80,1.0,6.0,6/23/2019
83968,19835318,Stunning bedroom in trendy Williamsburg!,77736603165,UNCONFIRMED,Nina,Brooklyn,Williamsburg,40.71407,-73.93936,United States,US,1,strict,Private room,2014.0,186,$37,30.0,2.0,7/6/2019

In [210]:
df.to_excel('excel_cleaned_data.xlsx', index=False)

In [211]:
df_excel = pd.read_excel('excel_cleaned_data.xlsx')
df_excel

,id,Name,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review
0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,0,strict,Private room,2020,966,$193,10,9,10/19/2021
1,38763192,Big One Bedroom Directly Across from Central P...,36257056231,UNCONFIRMED,Shaye,Manhattan,Upper West Side,40.79982,-73.96058,United States,US,0,strict,Entire home/apt,2013,286,$57,2,1,9/10/2017
2,38762639,Affordable 2 Bedroom on the UES!!!,83771419475,UNCONFIRMED,Zoe,Manhattan,Upper East Side,40.76644,-73.95486,United States,US,1,moderate,Entire home/apt,2010,858,$172,3,3,9/28/2017
3,38762087,Charming 1 br apartment,8856169091,VERIFIED,Andrew,Brooklyn,Bushwick,40.70587,-73.92358,United States,US,1,strict,Entire home/apt,2013,766,$153,2,13,4/15/2018
4,38760982,Artist's Room in Prime Bushwick,12458494587,VERIFIED,Lux,Brooklyn,Bushwick,40.70100,-73.91986,United States,US,0,moderate,Private room,2016,92,$18,1,77,7/7/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83964,19839184,Modern Living in Soho/Noho/West Village,62024966266,VERIFIED,Jeff,Manhattan,Greenwich Village,40.72674,-73.99673,United States,US,1,moderate,Entire home/apt,2021,451,$90,3,6,7/1/2019
83965,19838632,Central Park Spacious Room,74378693322,UNCONFIRMED,Hongzhi,Manhattan,Upper West Side,40.79908,-73.96215,United States,US,1,moderate,Private room,2017,763,$153,1,14,8/23/2018
83966,19837528,Prime East Village Manhattan w/ Beautiful Back...,58958151239,UNCONFIRMED,Thomas,Manhattan,East Village,40.72769,-73.98498,United States,US,1,moderate,Private room,2011,1121,$224,1,3,6/22/2019
83967,19836423,Brooklyn home away from home,36982711686,VERIFIED,Sofiya,Brooklyn,Sunset Park,40.66153,-73.99297,United States,US,0,strict,Private room,2018,399,$80,1,6,6/23/2019
83968,19835318,Stunning bedroom in trendy Williamsburg!,77736603165,UNCONFIRMED,Nina,Brooklyn,Williamsburg,40.71407,-73.93936,United States,US,1,strict,Private room,2014,186,$37,30,2,7/6/2019